// Code generated by ent, DO NOT EDIT.

package post

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the post type in the database.
	Label = "post"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldBrief holds the string denoting the brief field in the database.
	FieldBrief = "brief"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldContentHTML holds the string denoting the content_html field in the database.
	FieldContentHTML = "content_html"
	// FieldOtherByline holds the string denoting the other_byline field in the database.
	FieldOtherByline = "other_byline"
	// FieldPublishTime holds the string denoting the publish_time field in the database.
	FieldPublishTime = "publish_time"
	// FieldRenderVersion holds the string denoting the render_version field in the database.
	FieldRenderVersion = "render_version"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldSubtitle holds the string denoting the subtitle field in the database.
	FieldSubtitle = "subtitle"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// EdgeCategories holds the string denoting the categories edge name in mutations.
	EdgeCategories = "categories"
	// EdgeHeroImage holds the string denoting the hero_image edge name in mutations.
	EdgeHeroImage = "hero_image"
	// EdgeRelatedPosts holds the string denoting the related_posts edge name in mutations.
	EdgeRelatedPosts = "related_posts"
	// EdgeSection holds the string denoting the section edge name in mutations.
	EdgeSection = "section"
	// EdgeTags holds the string denoting the tags edge name in mutations.
	EdgeTags = "tags"
	// EdgeWriters holds the string denoting the writers edge name in mutations.
	EdgeWriters = "writers"
	// EdgeCreatedBy holds the string denoting the created_by edge name in mutations.
	EdgeCreatedBy = "created_by"
	// Table holds the table name of the post in the database.
	Table = "posts"
	// CategoriesTable is the table that holds the categories relation/edge. The primary key declared below.
	CategoriesTable = "post_categories"
	// CategoriesInverseTable is the table name for the Category entity.
	// It exists in this package in order to avoid circular dependency with the "category" package.
	CategoriesInverseTable = "categories"
	// HeroImageTable is the table that holds the hero_image relation/edge.
	HeroImageTable = "posts"
	// HeroImageInverseTable is the table name for the Photo entity.
	// It exists in this package in order to avoid circular dependency with the "photo" package.
	HeroImageInverseTable = "photos"
	// HeroImageColumn is the table column denoting the hero_image relation/edge.
	HeroImageColumn = "post_hero_image"
	// RelatedPostsTable is the table that holds the related_posts relation/edge. The primary key declared below.
	RelatedPostsTable = "post_related_posts"
	// SectionTable is the table that holds the section relation/edge.
	SectionTable = "posts"
	// SectionInverseTable is the table name for the Section entity.
	// It exists in this package in order to avoid circular dependency with the "section" package.
	SectionInverseTable = "sections"
	// SectionColumn is the table column denoting the section relation/edge.
	SectionColumn = "post_section"
	// TagsTable is the table that holds the tags relation/edge. The primary key declared below.
	TagsTable = "post_tags"
	// TagsInverseTable is the table name for the Tag entity.
	// It exists in this package in order to avoid circular dependency with the "tag" package.
	TagsInverseTable = "tags"
	// WritersTable is the table that holds the writers relation/edge. The primary key declared below.
	WritersTable = "post_writers"
	// WritersInverseTable is the table name for the Author entity.
	// It exists in this package in order to avoid circular dependency with the "author" package.
	WritersInverseTable = "authors"
	// CreatedByTable is the table that holds the created_by relation/edge.
	CreatedByTable = "posts"
	// CreatedByInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CreatedByInverseTable = "users"
	// CreatedByColumn is the table column denoting the created_by relation/edge.
	CreatedByColumn = "post_created_by"
)

// Columns holds all SQL columns for post fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldBrief,
	FieldContent,
	FieldContentHTML,
	FieldOtherByline,
	FieldPublishTime,
	FieldRenderVersion,
	FieldState,
	FieldSubtitle,
	FieldTitle,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "posts"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"post_hero_image",
	"post_section",
	"post_created_by",
}

var (
	// CategoriesPrimaryKey and CategoriesColumn2 are the table columns denoting the
	// primary key for the categories relation (M2M).
	CategoriesPrimaryKey = []string{"post_id", "category_id"}
	// RelatedPostsPrimaryKey and RelatedPostsColumn2 are the table columns denoting the
	// primary key for the related_posts relation (M2M).
	RelatedPostsPrimaryKey = []string{"post_id", "related_post_id"}
	// TagsPrimaryKey and TagsColumn2 are the table columns denoting the
	// primary key for the tags relation (M2M).
	TagsPrimaryKey = []string{"post_id", "tag_id"}
	// WritersPrimaryKey and WritersColumn2 are the table columns denoting the
	// primary key for the writers relation (M2M).
	WritersPrimaryKey = []string{"post_id", "author_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultRenderVersion holds the default value on creation for the "render_version" field.
	DefaultRenderVersion int
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
)

// State defines the type for the "state" enum field.
type State string

// StateDraft is the default value of the State enum.
const DefaultState = StateDraft

// State values.
const (
	StateDraft     State = "draft"
	StateScheduled State = "scheduled"
	StatePublished State = "published"
	StateArchived  State = "archived"
	StateInvisible State = "invisible"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StateDraft, StateScheduled, StatePublished, StateArchived, StateInvisible:
		return nil
	default:
		return fmt.Errorf("post: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the Post queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByContentHTML orders the results by the content_html field.
func ByContentHTML(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentHTML, opts...).ToFunc()
}

// ByOtherByline orders the results by the other_byline field.
func ByOtherByline(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOtherByline, opts...).ToFunc()
}

// ByPublishTime orders the results by the publish_time field.
func ByPublishTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishTime, opts...).ToFunc()
}

// ByRenderVersion orders the results by the render_version field.
func ByRenderVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRenderVersion, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// BySubtitle orders the results by the subtitle field.
func BySubtitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubtitle, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByCategoriesCount orders the results by categories count.
func ByCategoriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCategoriesStep(), opts...)
	}
}

// ByCategories orders the results by categories terms.
func ByCategories(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCategoriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByHeroImageField orders the results by hero_image field.
func ByHeroImageField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHeroImageStep(), sql.OrderByField(field, opts...))
	}
}

// ByRelatedPostsCount orders the results by related_posts count.
func ByRelatedPostsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRelatedPostsStep(), opts...)
	}
}

// ByRelatedPosts orders the results by related_posts terms.
func ByRelatedPosts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRelatedPostsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySectionField orders the results by section field.
func BySectionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSectionStep(), sql.OrderByField(field, opts...))
	}
}

// ByTagsCount orders the results by tags count.
func ByTagsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTagsStep(), opts...)
	}
}

// ByTags orders the results by tags terms.
func ByTags(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTagsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByWritersCount orders the results by writers count.
func ByWritersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newWritersStep(), opts...)
	}
}

// ByWriters orders the results by writers terms.
func ByWriters(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWritersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCreatedByField orders the results by created_by field.
func ByCreatedByField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatedByStep(), sql.OrderByField(field, opts...))
	}
}
func newCategoriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CategoriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, CategoriesTable, CategoriesPrimaryKey...),
	)
}
func newHeroImageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HeroImageInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, HeroImageTable, HeroImageColumn),
	)
}
func newRelatedPostsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, RelatedPostsTable, RelatedPostsPrimaryKey...),
	)
}
func newSectionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SectionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, SectionTable, SectionColumn),
	)
}
func newTagsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TagsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, TagsTable, TagsPrimaryKey...),
	)
}
func newWritersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WritersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, WritersTable, WritersPrimaryKey...),
	)
}
func newCreatedByStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatedByInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, CreatedByTable, CreatedByColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e State) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *State) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = State(str)
	if err := StateValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid State", str)
	}
	return nil
}
