// Code generated by ent, DO NOT EDIT.

package post

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/hcchien/nl/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldUpdatedAt, v))
}

// ContentHTML applies equality check predicate on the "content_html" field. It's identical to ContentHTMLEQ.
func ContentHTML(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldContentHTML, v))
}

// OtherByline applies equality check predicate on the "other_byline" field. It's identical to OtherBylineEQ.
func OtherByline(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldOtherByline, v))
}

// PublishTime applies equality check predicate on the "publish_time" field. It's identical to PublishTimeEQ.
func PublishTime(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldPublishTime, v))
}

// RenderVersion applies equality check predicate on the "render_version" field. It's identical to RenderVersionEQ.
func RenderVersion(v int) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldRenderVersion, v))
}

// Subtitle applies equality check predicate on the "subtitle" field. It's identical to SubtitleEQ.
func Subtitle(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldSubtitle, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldTitle, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldUpdatedAt, v))
}

// BriefIsNil applies the IsNil predicate on the "brief" field.
func BriefIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldBrief))
}

// BriefNotNil applies the NotNil predicate on the "brief" field.
func BriefNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldBrief))
}

// ContentIsNil applies the IsNil predicate on the "content" field.
func ContentIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldContent))
}

// ContentNotNil applies the NotNil predicate on the "content" field.
func ContentNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldContent))
}

// ContentHTMLEQ applies the EQ predicate on the "content_html" field.
func ContentHTMLEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldContentHTML, v))
}

// ContentHTMLNEQ applies the NEQ predicate on the "content_html" field.
func ContentHTMLNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldContentHTML, v))
}

// ContentHTMLIn applies the In predicate on the "content_html" field.
func ContentHTMLIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldContentHTML, vs...))
}

// ContentHTMLNotIn applies the NotIn predicate on the "content_html" field.
func ContentHTMLNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldContentHTML, vs...))
}

// ContentHTMLGT applies the GT predicate on the "content_html" field.
func ContentHTMLGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldContentHTML, v))
}

// ContentHTMLGTE applies the GTE predicate on the "content_html" field.
func ContentHTMLGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldContentHTML, v))
}

// ContentHTMLLT applies the LT predicate on the "content_html" field.
func ContentHTMLLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldContentHTML, v))
}

// ContentHTMLLTE applies the LTE predicate on the "content_html" field.
func ContentHTMLLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldContentHTML, v))
}

// ContentHTMLContains applies the Contains predicate on the "content_html" field.
func ContentHTMLContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldContentHTML, v))
}

// ContentHTMLHasPrefix applies the HasPrefix predicate on the "content_html" field.
func ContentHTMLHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldContentHTML, v))
}

// ContentHTMLHasSuffix applies the HasSuffix predicate on the "content_html" field.
func ContentHTMLHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldContentHTML, v))
}

// ContentHTMLIsNil applies the IsNil predicate on the "content_html" field.
func ContentHTMLIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldContentHTML))
}

// ContentHTMLNotNil applies the NotNil predicate on the "content_html" field.
func ContentHTMLNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldContentHTML))
}

// ContentHTMLEqualFold applies the EqualFold predicate on the "content_html" field.
func ContentHTMLEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldContentHTML, v))
}

// ContentHTMLContainsFold applies the ContainsFold predicate on the "content_html" field.
func ContentHTMLContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldContentHTML, v))
}

// OtherBylineEQ applies the EQ predicate on the "other_byline" field.
func OtherBylineEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldOtherByline, v))
}

// OtherBylineNEQ applies the NEQ predicate on the "other_byline" field.
func OtherBylineNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldOtherByline, v))
}

// OtherBylineIn applies the In predicate on the "other_byline" field.
func OtherBylineIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldOtherByline, vs...))
}

// OtherBylineNotIn applies the NotIn predicate on the "other_byline" field.
func OtherBylineNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldOtherByline, vs...))
}

// OtherBylineGT applies the GT predicate on the "other_byline" field.
func OtherBylineGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldOtherByline, v))
}

// OtherBylineGTE applies the GTE predicate on the "other_byline" field.
func OtherBylineGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldOtherByline, v))
}

// OtherBylineLT applies the LT predicate on the "other_byline" field.
func OtherBylineLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldOtherByline, v))
}

// OtherBylineLTE applies the LTE predicate on the "other_byline" field.
func OtherBylineLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldOtherByline, v))
}

// OtherBylineContains applies the Contains predicate on the "other_byline" field.
func OtherBylineContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldOtherByline, v))
}

// OtherBylineHasPrefix applies the HasPrefix predicate on the "other_byline" field.
func OtherBylineHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldOtherByline, v))
}

// OtherBylineHasSuffix applies the HasSuffix predicate on the "other_byline" field.
func OtherBylineHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldOtherByline, v))
}

// OtherBylineIsNil applies the IsNil predicate on the "other_byline" field.
func OtherBylineIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldOtherByline))
}

// OtherBylineNotNil applies the NotNil predicate on the "other_byline" field.
func OtherBylineNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldOtherByline))
}

// OtherBylineEqualFold applies the EqualFold predicate on the "other_byline" field.
func OtherBylineEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldOtherByline, v))
}

// OtherBylineContainsFold applies the ContainsFold predicate on the "other_byline" field.
func OtherBylineContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldOtherByline, v))
}

// PublishTimeEQ applies the EQ predicate on the "publish_time" field.
func PublishTimeEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldPublishTime, v))
}

// PublishTimeNEQ applies the NEQ predicate on the "publish_time" field.
func PublishTimeNEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldPublishTime, v))
}

// PublishTimeIn applies the In predicate on the "publish_time" field.
func PublishTimeIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldPublishTime, vs...))
}

// PublishTimeNotIn applies the NotIn predicate on the "publish_time" field.
func PublishTimeNotIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldPublishTime, vs...))
}

// PublishTimeGT applies the GT predicate on the "publish_time" field.
func PublishTimeGT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldPublishTime, v))
}

// PublishTimeGTE applies the GTE predicate on the "publish_time" field.
func PublishTimeGTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldPublishTime, v))
}

// PublishTimeLT applies the LT predicate on the "publish_time" field.
func PublishTimeLT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldPublishTime, v))
}

// PublishTimeLTE applies the LTE predicate on the "publish_time" field.
func PublishTimeLTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldPublishTime, v))
}

// PublishTimeIsNil applies the IsNil predicate on the "publish_time" field.
func PublishTimeIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldPublishTime))
}

// PublishTimeNotNil applies the NotNil predicate on the "publish_time" field.
func PublishTimeNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldPublishTime))
}

// RenderVersionEQ applies the EQ predicate on the "render_version" field.
func RenderVersionEQ(v int) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldRenderVersion, v))
}

// RenderVersionNEQ applies the NEQ predicate on the "render_version" field.
func RenderVersionNEQ(v int) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldRenderVersion, v))
}

// RenderVersionIn applies the In predicate on the "render_version" field.
func RenderVersionIn(vs ...int) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldRenderVersion, vs...))
}

// RenderVersionNotIn applies the NotIn predicate on the "render_version" field.
func RenderVersionNotIn(vs ...int) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldRenderVersion, vs...))
}

// RenderVersionGT applies the GT predicate on the "render_version" field.
func RenderVersionGT(v int) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldRenderVersion, v))
}

// RenderVersionGTE applies the GTE predicate on the "render_version" field.
func RenderVersionGTE(v int) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldRenderVersion, v))
}

// RenderVersionLT applies the LT predicate on the "render_version" field.
func RenderVersionLT(v int) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldRenderVersion, v))
}

// RenderVersionLTE applies the LTE predicate on the "render_version" field.
func RenderVersionLTE(v int) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldRenderVersion, v))
}

// RenderVersionIsNil applies the IsNil predicate on the "render_version" field.
func RenderVersionIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldRenderVersion))
}

// RenderVersionNotNil applies the NotNil predicate on the "render_version" field.
func RenderVersionNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldRenderVersion))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldState, vs...))
}

// SubtitleEQ applies the EQ predicate on the "subtitle" field.
func SubtitleEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldSubtitle, v))
}

// SubtitleNEQ applies the NEQ predicate on the "subtitle" field.
func SubtitleNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldSubtitle, v))
}

// SubtitleIn applies the In predicate on the "subtitle" field.
func SubtitleIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldSubtitle, vs...))
}

// SubtitleNotIn applies the NotIn predicate on the "subtitle" field.
func SubtitleNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldSubtitle, vs...))
}

// SubtitleGT applies the GT predicate on the "subtitle" field.
func SubtitleGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldSubtitle, v))
}

// SubtitleGTE applies the GTE predicate on the "subtitle" field.
func SubtitleGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldSubtitle, v))
}

// SubtitleLT applies the LT predicate on the "subtitle" field.
func SubtitleLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldSubtitle, v))
}

// SubtitleLTE applies the LTE predicate on the "subtitle" field.
func SubtitleLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldSubtitle, v))
}

// SubtitleContains applies the Contains predicate on the "subtitle" field.
func SubtitleContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldSubtitle, v))
}

// SubtitleHasPrefix applies the HasPrefix predicate on the "subtitle" field.
func SubtitleHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldSubtitle, v))
}

// SubtitleHasSuffix applies the HasSuffix predicate on the "subtitle" field.
func SubtitleHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldSubtitle, v))
}

// SubtitleIsNil applies the IsNil predicate on the "subtitle" field.
func SubtitleIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldSubtitle))
}

// SubtitleNotNil applies the NotNil predicate on the "subtitle" field.
func SubtitleNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldSubtitle))
}

// SubtitleEqualFold applies the EqualFold predicate on the "subtitle" field.
func SubtitleEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldSubtitle, v))
}

// SubtitleContainsFold applies the ContainsFold predicate on the "subtitle" field.
func SubtitleContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldSubtitle, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldTitle, v))
}

// HasCategories applies the HasEdge predicate on the "categories" edge.
func HasCategories() predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, CategoriesTable, CategoriesPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCategoriesWith applies the HasEdge predicate on the "categories" edge with a given conditions (other predicates).
func HasCategoriesWith(preds ...predicate.Category) predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := newCategoriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasHeroImage applies the HasEdge predicate on the "hero_image" edge.
func HasHeroImage() predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, HeroImageTable, HeroImageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHeroImageWith applies the HasEdge predicate on the "hero_image" edge with a given conditions (other predicates).
func HasHeroImageWith(preds ...predicate.Photo) predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := newHeroImageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRelatedPosts applies the HasEdge predicate on the "related_posts" edge.
func HasRelatedPosts() predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, RelatedPostsTable, RelatedPostsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelatedPostsWith applies the HasEdge predicate on the "related_posts" edge with a given conditions (other predicates).
func HasRelatedPostsWith(preds ...predicate.Post) predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := newRelatedPostsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSection applies the HasEdge predicate on the "section" edge.
func HasSection() predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, SectionTable, SectionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSectionWith applies the HasEdge predicate on the "section" edge with a given conditions (other predicates).
func HasSectionWith(preds ...predicate.Section) predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := newSectionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTags applies the HasEdge predicate on the "tags" edge.
func HasTags() predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, TagsTable, TagsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTagsWith applies the HasEdge predicate on the "tags" edge with a given conditions (other predicates).
func HasTagsWith(preds ...predicate.Tag) predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := newTagsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWriters applies the HasEdge predicate on the "writers" edge.
func HasWriters() predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, WritersTable, WritersPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWritersWith applies the HasEdge predicate on the "writers" edge with a given conditions (other predicates).
func HasWritersWith(preds ...predicate.Author) predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := newWritersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCreatedBy applies the HasEdge predicate on the "created_by" edge.
func HasCreatedBy() predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, CreatedByTable, CreatedByColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatedByWith applies the HasEdge predicate on the "created_by" edge with a given conditions (other predicates).
func HasCreatedByWith(preds ...predicate.User) predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := newCreatedByStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Post) predicate.Post {
	return predicate.Post(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Post) predicate.Post {
	return predicate.Post(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Post) predicate.Post {
	return predicate.Post(sql.NotPredicates(p))
}
