// Package codegen 將 nl DSL 宣告展開成編譯期 artifacts：
//
//	ent/schema/zz_gen_lists.go   ent schema（一個 list 一個 type）
//	graph/lists.graphqls         CRUD mutations（input types 由 entgql 生成）
//	graph/lists.resolvers.go     CRUD resolver 實作
//	access/zz_gen_owner.go       owner-scoped 權限的 typed helpers
//
// access 規則與 MCP metadata 不需要 codegen —— 執行期直接讀 nl registry。
package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/hcchien/nl/nl"
)

const header = "// Code generated by nl gen. DO NOT EDIT.\n\n"

// Generate 將所有已註冊的 lists 展開到 root（repo 根目錄）。
func Generate(root string) error {
	lists := nl.Registry()
	if len(lists) == 0 {
		return fmt.Errorf("no lists registered — blank-import your lists package")
	}
	files := map[string]string{
		"ent/schema/zz_gen_lists.go": entSchema(lists),
		"graph/lists.graphqls":       graphqls(lists),
		"graph/lists.resolvers.go":   resolvers(lists),
		"access/zz_gen_owner.go":     ownerHelpers(lists),
	}
	for rel, content := range files {
		path := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", rel, err)
		}
	}
	return nil
}

// ---- ent schema ----

func entSchema(lists []*nl.ListDef) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("package schema\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"regexp\"\n\n")
	b.WriteString("\t\"entgo.io/contrib/entgql\"\n")
	b.WriteString("\t\"entgo.io/ent\"\n")
	b.WriteString("\t\"entgo.io/ent/schema\"\n")
	b.WriteString("\t\"entgo.io/ent/schema/edge\"\n")
	b.WriteString("\t\"entgo.io/ent/schema/field\"\n")
	b.WriteString(")\n\n")
	b.WriteString("var _ = regexp.MustCompile // 避免 regexp 未使用\n\n")

	for _, l := range lists {
		fmt.Fprintf(&b, "// %s：%s\n", l.Name, l.Description)
		fmt.Fprintf(&b, "type %s struct{ ent.Schema }\n\n", l.Name)
		fmt.Fprintf(&b, "func (%s) Mixin() []ent.Mixin { return []ent.Mixin{TimeMixin{}} }\n\n", l.Name)

		// Fields
		fmt.Fprintf(&b, "func (%s) Fields() []ent.Field {\n\treturn []ent.Field{\n", l.Name)
		for _, fname := range l.FieldOrder {
			f := l.Fields[fname]
			if f.Type == nl.TypeRelationship {
				continue
			}
			fmt.Fprintf(&b, "\t\t%s,\n", entField(fname, f))
		}
		b.WriteString("\t}\n}\n\n")

		// Edges
		edges := entEdges(l, lists)
		if len(edges) > 0 {
			fmt.Fprintf(&b, "func (%s) Edges() []ent.Edge {\n\treturn []ent.Edge{\n", l.Name)
			for _, e := range edges {
				fmt.Fprintf(&b, "\t\t%s,\n", e)
			}
			b.WriteString("\t}\n}\n\n")
		}

		// Annotations
		fmt.Fprintf(&b, "func (%s) Annotations() []schema.Annotation {\n", l.Name)
		b.WriteString("\treturn []schema.Annotation{\n")
		b.WriteString("\t\tentgql.QueryField(),\n")
		b.WriteString("\t\tentgql.RelayConnection(),\n")
		b.WriteString("\t\tentgql.Mutations(entgql.MutationCreate(), entgql.MutationUpdate()),\n")
		b.WriteString("\t}\n}\n\n")
	}
	return b.String()
}

func entField(name string, f nl.Field) string {
	col := snake(name)
	var s string
	switch f.Type {
	case nl.TypeText:
		s = fmt.Sprintf("field.Text(%q)", col)
		if f.Required {
			s += ".NotEmpty()"
		} else {
			s += ".Optional()"
		}
		if f.Match != "" {
			s += fmt.Sprintf(".Match(regexp.MustCompile(%q))", f.Match)
		}
	case nl.TypeInteger:
		s = fmt.Sprintf("field.Int(%q)", col)
		if f.Default != nil {
			s += fmt.Sprintf(".Default(%v)", f.Default)
		}
		if !f.Required {
			s += ".Optional()"
		}
	case nl.TypeBoolean:
		s = fmt.Sprintf("field.Bool(%q)", col)
		if f.Default != nil {
			s += fmt.Sprintf(".Default(%v)", f.Default)
		} else {
			s += ".Optional()"
		}
	case nl.TypeTimestamp:
		s = fmt.Sprintf("field.Time(%q)", col)
		if !f.Required {
			s += ".Optional().Nillable()"
		}
	case nl.TypeSelect:
		vals := make([]string, len(f.Enum))
		for i, v := range f.Enum {
			vals[i] = fmt.Sprintf("%q", v)
		}
		s = fmt.Sprintf("field.Enum(%q).Values(%s)", col, strings.Join(vals, ", "))
		if f.Default != nil {
			s += fmt.Sprintf(".Default(%q)", f.Default)
		}
	case nl.TypeRichText:
		s = fmt.Sprintf("field.JSON(%q, map[string]interface{}{}).Optional().Annotations(entgql.Type(\"JSON\"))", col)
		return s // JSON 欄位不吃下方通用修飾
	case nl.TypePassword:
		s = fmt.Sprintf("field.Text(%q).NotEmpty().Annotations(entgql.Skip(entgql.SkipType | entgql.SkipWhereInput | entgql.SkipOrderField))", col)
		return s
	default:
		panic(fmt.Sprintf("unsupported field type %q", f.Type))
	}
	if f.ReadOnly {
		s += fmt.Sprintf(".Annotations(entgql.Skip(entgql.SkipMutationCreateInput | entgql.SkipMutationUpdateInput | entgql.SkipWhereInput), entgql.MapsTo(%q))", name)
	}
	if f.Unique {
		s += ".Unique()"
	}
	if f.OrderKey != "" {
		s += fmt.Sprintf(".Annotations(entgql.OrderField(%q))", f.OrderKey)
	}
	return s
}

func entEdges(l *nl.ListDef, all []*nl.ListDef) []string {
	var edges []string
	// 自己宣告的關聯（owning To edge）
	for _, fname := range l.FieldOrder {
		f := l.Fields[fname]
		if f.Type != nl.TypeRelationship {
			continue
		}
		e := fmt.Sprintf("edge.To(%q, %s.Type)", snake(fname), f.Ref)
		if !f.Many {
			e += ".Unique()"
		}
		edges = append(edges, e)
	}
	// 其他 list 指向自己且宣告了 Inverse 的反向 edge
	for _, other := range all {
		var names []string
		for fname := range other.Fields {
			names = append(names, fname)
		}
		sort.Strings(names)
		for _, fname := range names {
			f := other.Fields[fname]
			if f.Type == nl.TypeRelationship && f.Ref == l.Name && f.Inverse != "" {
				edges = append(edges, fmt.Sprintf("edge.From(%q, %s.Type).Ref(%q)",
					snake(f.Inverse), other.Name, snake(fname)))
			}
		}
	}
	// createdBy 追蹤（不開放 GraphQL input）
	if l.TrackCreator {
		edges = append(edges,
			`edge.To("created_by", User.Type).Unique().Annotations(entgql.Skip(entgql.SkipMutationCreateInput | entgql.SkipMutationUpdateInput))`)
	}
	return edges
}

// ---- GraphQL schema ----

func graphqls(lists []*nl.ListDef) string {
	var b strings.Builder
	b.WriteString("# Code generated by nl gen. DO NOT EDIT.\n\n")
	if anyRichText(lists) {
		b.WriteString("\"\"\"ProseMirror document JSON\"\"\"\nscalar JSON\n\n")
	}
	b.WriteString("type Mutation {\n")
	for _, l := range lists {
		fmt.Fprintf(&b, "  create%s(input: Create%sInput!): %s!\n", l.Name, l.Name, l.Name)
		fmt.Fprintf(&b, "  update%s(id: ID!, input: Update%sInput!): %s!\n", l.Name, l.Name, l.Name)
		fmt.Fprintf(&b, "  delete%s(id: ID!): ID!\n", l.Name)
	}
	b.WriteString("}\n")
	return b.String()
}

func anyRichText(lists []*nl.ListDef) bool {
	for _, l := range lists {
		for _, f := range l.Fields {
			if f.Type == nl.TypeRichText {
				return true
			}
		}
	}
	return false
}

// ---- Resolvers ----

func resolvers(lists []*nl.ListDef) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("package graph\n\n")
	b.WriteString("import (\n\t\"context\"\n\n\t\"github.com/hcchien/nl/ent\"\n)\n\n")
	for _, l := range lists {
		n := l.Name
		fmt.Fprintf(&b, "// Create%s is the resolver for the create%s field.\n", n, n)
		fmt.Fprintf(&b, "func (r *mutationResolver) Create%s(ctx context.Context, input ent.Create%sInput) (*ent.%s, error) {\n", n, n, n)
		fmt.Fprintf(&b, "\treturn r.Client.%s.Create().SetInput(input).Save(ctx)\n}\n\n", n)
		fmt.Fprintf(&b, "// Update%s is the resolver for the update%s field.\n", n, n)
		fmt.Fprintf(&b, "func (r *mutationResolver) Update%s(ctx context.Context, id int, input ent.Update%sInput) (*ent.%s, error) {\n", n, n, n)
		fmt.Fprintf(&b, "\treturn r.Client.%s.UpdateOneID(id).SetInput(input).Save(ctx)\n}\n\n", n)
		fmt.Fprintf(&b, "// Delete%s is the resolver for the delete%s field.\n", n, n)
		fmt.Fprintf(&b, "func (r *mutationResolver) Delete%s(ctx context.Context, id int) (int, error) {\n", n)
		fmt.Fprintf(&b, "\tif err := r.Client.%s.DeleteOneID(id).Exec(ctx); err != nil {\n\t\treturn 0, err\n\t}\n\treturn id, nil\n}\n\n", n)
	}
	b.WriteString("// Mutation returns MutationResolver implementation.\n")
	b.WriteString("func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }\n\n")
	b.WriteString("type mutationResolver struct{ *Resolver }\n")
	return b.String()
}

// ---- Owner helpers（access package）----

func ownerHelpers(lists []*nl.ListDef) string {
	var tracked []*nl.ListDef
	for _, l := range lists {
		if l.TrackCreator {
			tracked = append(tracked, l)
		}
	}
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("package access\n\n")
	b.WriteString("import (\n\t\"context\"\n\n\t\"entgo.io/ent/dialect/sql\"\n\n")
	b.WriteString("\tgen \"github.com/hcchien/nl/ent\"\n")
	for _, l := range tracked {
		fmt.Fprintf(&b, "\t\"github.com/hcchien/nl/ent/%s\"\n", strings.ToLower(l.Name))
	}
	b.WriteString("\t\"github.com/hcchien/nl/ent/user\"\n")
	b.WriteString(")\n\n")

	b.WriteString("// ownerPredicate 回傳 list 的「createdBy = viewer」predicate。\n")
	b.WriteString("func ownerPredicate(list string, uid int) (func(*sql.Selector), bool) {\n\tswitch list {\n")
	for _, l := range tracked {
		fmt.Fprintf(&b, "\tcase %q:\n\t\treturn %s.HasCreatedByWith(user.IDEQ(uid)), true\n", l.Name, strings.ToLower(l.Name))
	}
	b.WriteString("\t}\n\treturn nil, false\n}\n\n")

	b.WriteString("// ownedExists 檢查單筆 mutation 的目標是否屬於 viewer；bulk mutation 回傳 single=false。\n")
	b.WriteString("func ownedExists(ctx context.Context, m gen.Mutation, uid int) (owned, single bool, err error) {\n\tswitch mm := m.(type) {\n")
	for _, l := range tracked {
		pkg := strings.ToLower(l.Name)
		fmt.Fprintf(&b, "\tcase *gen.%sMutation:\n", l.Name)
		fmt.Fprintf(&b, "\t\tid, ok := mm.ID()\n\t\tif !ok {\n\t\t\treturn false, false, nil\n\t\t}\n")
		fmt.Fprintf(&b, "\t\towned, err = mm.Client().%s.Query().Where(%s.ID(id), %s.HasCreatedByWith(user.IDEQ(uid))).Exist(ctx)\n", l.Name, pkg, pkg)
		b.WriteString("\t\treturn owned, true, err\n")
	}
	b.WriteString("\t}\n\treturn false, false, nil\n}\n\n")

	b.WriteString("// setCreator 在 create 時自動掛上 viewer（宣告了 nl.TrackCreator 的 lists）。\n")
	b.WriteString("func setCreator(m gen.Mutation, uid int) {\n\tswitch mm := m.(type) {\n")
	for _, l := range tracked {
		fmt.Fprintf(&b, "\tcase *gen.%sMutation:\n", l.Name)
		b.WriteString("\t\tif _, ok := mm.CreatedByID(); !ok {\n\t\t\tmm.SetCreatedByID(uid)\n\t\t}\n")
	}
	b.WriteString("\t}\n}\n")
	return b.String()
}

// snake 將 camelCase 轉為 snake_case（heroImage → hero_image）。
func snake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteRune(r - 'A' + 'a')
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}
