// Code generated by nl gen. DO NOT EDIT.

package schema

import (
	"regexp"

	"entgo.io/contrib/entgql"
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

var _ = regexp.MustCompile // 避免 regexp 未使用

// Author：作者/記者（非登入使用者）。
type Author struct{ ent.Schema }

func (Author) Mixin() []ent.Mixin { return []ent.Mixin{TimeMixin{}} }

func (Author) Fields() []ent.Field {
	return []ent.Field{
		field.Text("bio").Optional(),
		field.Text("name").NotEmpty(),
	}
}

func (Author) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("image", Photo.Type).Unique(),
		edge.From("posts", Post.Type).Ref("writers"),
	}
}

func (Author) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entgql.QueryField(),
		entgql.RelayConnection(),
		entgql.Mutations(entgql.MutationCreate(), entgql.MutationUpdate()),
	}
}

// Category：中分類，隸屬於一個 Section。
type Category struct{ ent.Schema }

func (Category) Mixin() []ent.Mixin { return []ent.Mixin{TimeMixin{}} }

func (Category) Fields() []ent.Field {
	return []ent.Field{
		field.Text("description").Optional(),
		field.Text("name").NotEmpty(),
		field.Text("slug").NotEmpty().Match(regexp.MustCompile("^[a-zA-Z0-9]+$")).Unique(),
	}
}

func (Category) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("section", Section.Type).Unique(),
		edge.From("posts", Post.Type).Ref("categories"),
	}
}

func (Category) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entgql.QueryField(),
		entgql.RelayConnection(),
		entgql.Mutations(entgql.MutationCreate(), entgql.MutationUpdate()),
	}
}

// Photo：圖片（v1 以 URL 表示）。
type Photo struct{ ent.Schema }

func (Photo) Mixin() []ent.Mixin { return []ent.Mixin{TimeMixin{}} }

func (Photo) Fields() []ent.Field {
	return []ent.Field{
		field.Text("description").Optional(),
		field.Text("name").NotEmpty(),
		field.Text("url").Optional(),
	}
}

func (Photo) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entgql.QueryField(),
		entgql.RelayConnection(),
		entgql.Mutations(entgql.MutationCreate(), entgql.MutationUpdate()),
	}
}

// Post：文章。editor/contributor 僅能查詢與修改自己建立的文章；contributor 不可修改 state。
type Post struct{ ent.Schema }

func (Post) Mixin() []ent.Mixin { return []ent.Mixin{TimeMixin{}} }

func (Post) Fields() []ent.Field {
	return []ent.Field{
		field.JSON("brief", map[string]interface{}{}).Optional().Annotations(entgql.Type("JSON")),
		field.JSON("content", map[string]interface{}{}).Optional().Annotations(entgql.Type("JSON")),
		field.Text("content_html").Optional().Annotations(entgql.Skip(entgql.SkipMutationCreateInput | entgql.SkipMutationUpdateInput | entgql.SkipWhereInput), entgql.MapsTo("contentHtml")),
		field.Text("other_byline").Optional(),
		field.Time("publish_time").Optional().Nillable().Annotations(entgql.OrderField("PUBLISH_TIME")),
		field.Int("render_version").Default(0).Optional().Annotations(entgql.Skip(entgql.SkipMutationCreateInput | entgql.SkipMutationUpdateInput | entgql.SkipWhereInput), entgql.MapsTo("renderVersion")),
		field.Enum("state").Values("draft", "scheduled", "published", "archived", "invisible").Default("draft"),
		field.Text("subtitle").Optional(),
		field.Text("title").NotEmpty(),
	}
}

func (Post) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("categories", Category.Type),
		edge.To("hero_image", Photo.Type).Unique(),
		edge.To("related_posts", Post.Type),
		edge.To("section", Section.Type).Unique(),
		edge.To("tags", Tag.Type),
		edge.To("writers", Author.Type),
		edge.To("created_by", User.Type).Unique().Annotations(entgql.Skip(entgql.SkipMutationCreateInput | entgql.SkipMutationUpdateInput)),
	}
}

func (Post) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entgql.QueryField(),
		entgql.RelayConnection(),
		entgql.Mutations(entgql.MutationCreate(), entgql.MutationUpdate()),
	}
}

// Section：大分類。
type Section struct{ ent.Schema }

func (Section) Mixin() []ent.Mixin { return []ent.Mixin{TimeMixin{}} }

func (Section) Fields() []ent.Field {
	return []ent.Field{
		field.Text("description").Optional(),
		field.Text("name").NotEmpty(),
		field.Text("slug").NotEmpty().Match(regexp.MustCompile("^[a-zA-Z0-9]+$")).Unique(),
	}
}

func (Section) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("categories", Category.Type).Ref("section"),
		edge.From("posts", Post.Type).Ref("section"),
	}
}

func (Section) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entgql.QueryField(),
		entgql.RelayConnection(),
		entgql.Mutations(entgql.MutationCreate(), entgql.MutationUpdate()),
	}
}

// Tag：標籤。
type Tag struct{ ent.Schema }

func (Tag) Mixin() []ent.Mixin { return []ent.Mixin{TimeMixin{}} }

func (Tag) Fields() []ent.Field {
	return []ent.Field{
		field.Text("brief").Optional(),
		field.Bool("is_featured").Default(false),
		field.Text("name").NotEmpty().Unique(),
		field.Int("sort_order").Optional().Annotations(entgql.OrderField("SORT_ORDER")),
	}
}

func (Tag) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("posts", Post.Type).Ref("tags"),
	}
}

func (Tag) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entgql.QueryField(),
		entgql.RelayConnection(),
		entgql.Mutations(entgql.MutationCreate(), entgql.MutationUpdate()),
	}
}

// User：CMS 使用者。email 僅 admin/moderator 可讀（本人除外）。
type User struct{ ent.Schema }

func (User) Mixin() []ent.Mixin { return []ent.Mixin{TimeMixin{}} }

func (User) Fields() []ent.Field {
	return []ent.Field{
		field.Text("email").NotEmpty().Unique(),
		field.Text("name").NotEmpty(),
		field.Text("password").NotEmpty().Annotations(entgql.Skip(entgql.SkipType | entgql.SkipWhereInput | entgql.SkipOrderField)),
		field.Enum("role").Values("admin", "moderator", "editor", "contributor"),
	}
}

func (User) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entgql.QueryField(),
		entgql.RelayConnection(),
		entgql.Mutations(entgql.MutationCreate(), entgql.MutationUpdate()),
	}
}

