// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/hcchien/nl/ent"
)

type APIKeyPayload struct {
	// 明文金鑰，僅於簽發當下回傳一次
	Key  string `json:"key"`
	Name string `json:"name"`
}

type AuthPayload struct {
	Token string    `json:"token"`
	User  *ent.User `json:"user"`
}

// 網站專用金鑰；key 僅簽發時回傳，id 用於撤銷。
type ContentAPIKeyPayload struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Key  string `json:"key"`
}
