// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "scope", Type: field.TypeEnum, Enums: []string{"cms", "content:read"}, Default: "cms"},
		{Name: "name", Type: field.TypeString},
		{Name: "key_hash", Type: field.TypeString, Unique: true},
		{Name: "api_key_user", Type: field.TypeInt},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_keys_users_user",
				Columns:    []*schema.Column{APIKeysColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// AuthorsColumns holds the columns for the "authors" table.
	AuthorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "bio", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "name", Type: field.TypeString, Size: 2147483647},
		{Name: "author_image", Type: field.TypeInt, Nullable: true},
	}
	// AuthorsTable holds the schema information for the "authors" table.
	AuthorsTable = &schema.Table{
		Name:       "authors",
		Columns:    AuthorsColumns,
		PrimaryKey: []*schema.Column{AuthorsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "authors_photos_image",
				Columns:    []*schema.Column{AuthorsColumns[5]},
				RefColumns: []*schema.Column{PhotosColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "name", Type: field.TypeString, Size: 2147483647},
		{Name: "slug", Type: field.TypeString, Unique: true, Size: 2147483647},
		{Name: "category_section", Type: field.TypeInt, Nullable: true},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "categories_sections_section",
				Columns:    []*schema.Column{CategoriesColumns[6]},
				RefColumns: []*schema.Column{SectionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// OauthClientsColumns holds the columns for the "oauth_clients" table.
	OauthClientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "client_id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "redirect_uris", Type: field.TypeJSON},
	}
	// OauthClientsTable holds the schema information for the "oauth_clients" table.
	OauthClientsTable = &schema.Table{
		Name:       "oauth_clients",
		Columns:    OauthClientsColumns,
		PrimaryKey: []*schema.Column{OauthClientsColumns[0]},
	}
	// OauthCodesColumns holds the columns for the "oauth_codes" table.
	OauthCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "code_hash", Type: field.TypeString, Unique: true},
		{Name: "client_id", Type: field.TypeString},
		{Name: "redirect_uri", Type: field.TypeString},
		{Name: "code_challenge", Type: field.TypeString},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "oauth_code_user", Type: field.TypeInt},
	}
	// OauthCodesTable holds the schema information for the "oauth_codes" table.
	OauthCodesTable = &schema.Table{
		Name:       "oauth_codes",
		Columns:    OauthCodesColumns,
		PrimaryKey: []*schema.Column{OauthCodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "oauth_codes_users_user",
				Columns:    []*schema.Column{OauthCodesColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// OauthRefreshesColumns holds the columns for the "oauth_refreshes" table.
	OauthRefreshesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "client_id", Type: field.TypeString},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "oauth_refresh_user", Type: field.TypeInt},
	}
	// OauthRefreshesTable holds the schema information for the "oauth_refreshes" table.
	OauthRefreshesTable = &schema.Table{
		Name:       "oauth_refreshes",
		Columns:    OauthRefreshesColumns,
		PrimaryKey: []*schema.Column{OauthRefreshesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "oauth_refreshes_users_user",
				Columns:    []*schema.Column{OauthRefreshesColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PhotosColumns holds the columns for the "photos" table.
	PhotosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "name", Type: field.TypeString, Size: 2147483647},
		{Name: "url", Type: field.TypeString, Nullable: true, Size: 2147483647},
	}
	// PhotosTable holds the schema information for the "photos" table.
	PhotosTable = &schema.Table{
		Name:       "photos",
		Columns:    PhotosColumns,
		PrimaryKey: []*schema.Column{PhotosColumns[0]},
	}
	// PostsColumns holds the columns for the "posts" table.
	PostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "brief", Type: field.TypeJSON, Nullable: true},
		{Name: "content", Type: field.TypeJSON, Nullable: true},
		{Name: "content_html", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "other_byline", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "publish_time", Type: field.TypeTime, Nullable: true},
		{Name: "render_version", Type: field.TypeInt, Nullable: true, Default: 0},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"draft", "scheduled", "published", "archived", "invisible"}, Default: "draft"},
		{Name: "subtitle", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "title", Type: field.TypeString, Size: 2147483647},
		{Name: "post_hero_image", Type: field.TypeInt, Nullable: true},
		{Name: "post_section", Type: field.TypeInt, Nullable: true},
		{Name: "post_created_by", Type: field.TypeInt, Nullable: true},
	}
	// PostsTable holds the schema information for the "posts" table.
	PostsTable = &schema.Table{
		Name:       "posts",
		Columns:    PostsColumns,
		PrimaryKey: []*schema.Column{PostsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "posts_photos_hero_image",
				Columns:    []*schema.Column{PostsColumns[12]},
				RefColumns: []*schema.Column{PhotosColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "posts_sections_section",
				Columns:    []*schema.Column{PostsColumns[13]},
				RefColumns: []*schema.Column{SectionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "posts_users_created_by",
				Columns:    []*schema.Column{PostsColumns[14]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SectionsColumns holds the columns for the "sections" table.
	SectionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "name", Type: field.TypeString, Size: 2147483647},
		{Name: "slug", Type: field.TypeString, Unique: true, Size: 2147483647},
	}
	// SectionsTable holds the schema information for the "sections" table.
	SectionsTable = &schema.Table{
		Name:       "sections",
		Columns:    SectionsColumns,
		PrimaryKey: []*schema.Column{SectionsColumns[0]},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "brief", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "is_featured", Type: field.TypeBool, Default: false},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 2147483647},
		{Name: "sort_order", Type: field.TypeInt, Nullable: true},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 2147483647},
		{Name: "name", Type: field.TypeString, Size: 2147483647},
		{Name: "password", Type: field.TypeString, Size: 2147483647},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "moderator", "editor", "contributor"}},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// PostCategoriesColumns holds the columns for the "post_categories" table.
	PostCategoriesColumns = []*schema.Column{
		{Name: "post_id", Type: field.TypeInt},
		{Name: "category_id", Type: field.TypeInt},
	}
	// PostCategoriesTable holds the schema information for the "post_categories" table.
	PostCategoriesTable = &schema.Table{
		Name:       "post_categories",
		Columns:    PostCategoriesColumns,
		PrimaryKey: []*schema.Column{PostCategoriesColumns[0], PostCategoriesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "post_categories_post_id",
				Columns:    []*schema.Column{PostCategoriesColumns[0]},
				RefColumns: []*schema.Column{PostsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "post_categories_category_id",
				Columns:    []*schema.Column{PostCategoriesColumns[1]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// PostRelatedPostsColumns holds the columns for the "post_related_posts" table.
	PostRelatedPostsColumns = []*schema.Column{
		{Name: "post_id", Type: field.TypeInt},
		{Name: "related_post_id", Type: field.TypeInt},
	}
	// PostRelatedPostsTable holds the schema information for the "post_related_posts" table.
	PostRelatedPostsTable = &schema.Table{
		Name:       "post_related_posts",
		Columns:    PostRelatedPostsColumns,
		PrimaryKey: []*schema.Column{PostRelatedPostsColumns[0], PostRelatedPostsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "post_related_posts_post_id",
				Columns:    []*schema.Column{PostRelatedPostsColumns[0]},
				RefColumns: []*schema.Column{PostsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "post_related_posts_related_post_id",
				Columns:    []*schema.Column{PostRelatedPostsColumns[1]},
				RefColumns: []*schema.Column{PostsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// PostTagsColumns holds the columns for the "post_tags" table.
	PostTagsColumns = []*schema.Column{
		{Name: "post_id", Type: field.TypeInt},
		{Name: "tag_id", Type: field.TypeInt},
	}
	// PostTagsTable holds the schema information for the "post_tags" table.
	PostTagsTable = &schema.Table{
		Name:       "post_tags",
		Columns:    PostTagsColumns,
		PrimaryKey: []*schema.Column{PostTagsColumns[0], PostTagsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "post_tags_post_id",
				Columns:    []*schema.Column{PostTagsColumns[0]},
				RefColumns: []*schema.Column{PostsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "post_tags_tag_id",
				Columns:    []*schema.Column{PostTagsColumns[1]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// PostWritersColumns holds the columns for the "post_writers" table.
	PostWritersColumns = []*schema.Column{
		{Name: "post_id", Type: field.TypeInt},
		{Name: "author_id", Type: field.TypeInt},
	}
	// PostWritersTable holds the schema information for the "post_writers" table.
	PostWritersTable = &schema.Table{
		Name:       "post_writers",
		Columns:    PostWritersColumns,
		PrimaryKey: []*schema.Column{PostWritersColumns[0], PostWritersColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "post_writers_post_id",
				Columns:    []*schema.Column{PostWritersColumns[0]},
				RefColumns: []*schema.Column{PostsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "post_writers_author_id",
				Columns:    []*schema.Column{PostWritersColumns[1]},
				RefColumns: []*schema.Column{AuthorsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIKeysTable,
		AuthorsTable,
		CategoriesTable,
		OauthClientsTable,
		OauthCodesTable,
		OauthRefreshesTable,
		PhotosTable,
		PostsTable,
		SectionsTable,
		TagsTable,
		UsersTable,
		PostCategoriesTable,
		PostRelatedPostsTable,
		PostTagsTable,
		PostWritersTable,
	}
)

func init() {
	APIKeysTable.ForeignKeys[0].RefTable = UsersTable
	AuthorsTable.ForeignKeys[0].RefTable = PhotosTable
	CategoriesTable.ForeignKeys[0].RefTable = SectionsTable
	OauthCodesTable.ForeignKeys[0].RefTable = UsersTable
	OauthRefreshesTable.ForeignKeys[0].RefTable = UsersTable
	PostsTable.ForeignKeys[0].RefTable = PhotosTable
	PostsTable.ForeignKeys[1].RefTable = SectionsTable
	PostsTable.ForeignKeys[2].RefTable = UsersTable
	PostCategoriesTable.ForeignKeys[0].RefTable = PostsTable
	PostCategoriesTable.ForeignKeys[1].RefTable = CategoriesTable
	PostRelatedPostsTable.ForeignKeys[0].RefTable = PostsTable
	PostRelatedPostsTable.ForeignKeys[1].RefTable = PostsTable
	PostTagsTable.ForeignKeys[0].RefTable = PostsTable
	PostTagsTable.ForeignKeys[1].RefTable = TagsTable
	PostWritersTable.ForeignKeys[0].RefTable = PostsTable
	PostWritersTable.ForeignKeys[1].RefTable = AuthorsTable
}
