// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hcchien/nl/ent/author"
	"github.com/hcchien/nl/ent/category"
	"github.com/hcchien/nl/ent/photo"
	"github.com/hcchien/nl/ent/post"
	"github.com/hcchien/nl/ent/predicate"
	"github.com/hcchien/nl/ent/section"
	"github.com/hcchien/nl/ent/tag"
	"github.com/hcchien/nl/ent/user"
)

// PostUpdate is the builder for updating Post entities.
type PostUpdate struct {
	config
	hooks    []Hook
	mutation *PostMutation
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdate) Where(ps ...predicate.Post) *PostUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdate) SetUpdatedAt(v time.Time) *PostUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBrief sets the "brief" field.
func (_u *PostUpdate) SetBrief(v map[string]interface{}) *PostUpdate {
	_u.mutation.SetBrief(v)
	return _u
}

// ClearBrief clears the value of the "brief" field.
func (_u *PostUpdate) ClearBrief() *PostUpdate {
	_u.mutation.ClearBrief()
	return _u
}

// SetContent sets the "content" field.
func (_u *PostUpdate) SetContent(v map[string]interface{}) *PostUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *PostUpdate) ClearContent() *PostUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetContentHTML sets the "content_html" field.
func (_u *PostUpdate) SetContentHTML(v string) *PostUpdate {
	_u.mutation.SetContentHTML(v)
	return _u
}

// SetNillableContentHTML sets the "content_html" field if the given value is not nil.
func (_u *PostUpdate) SetNillableContentHTML(v *string) *PostUpdate {
	if v != nil {
		_u.SetContentHTML(*v)
	}
	return _u
}

// ClearContentHTML clears the value of the "content_html" field.
func (_u *PostUpdate) ClearContentHTML() *PostUpdate {
	_u.mutation.ClearContentHTML()
	return _u
}

// SetOtherByline sets the "other_byline" field.
func (_u *PostUpdate) SetOtherByline(v string) *PostUpdate {
	_u.mutation.SetOtherByline(v)
	return _u
}

// SetNillableOtherByline sets the "other_byline" field if the given value is not nil.
func (_u *PostUpdate) SetNillableOtherByline(v *string) *PostUpdate {
	if v != nil {
		_u.SetOtherByline(*v)
	}
	return _u
}

// ClearOtherByline clears the value of the "other_byline" field.
func (_u *PostUpdate) ClearOtherByline() *PostUpdate {
	_u.mutation.ClearOtherByline()
	return _u
}

// SetPublishTime sets the "publish_time" field.
func (_u *PostUpdate) SetPublishTime(v time.Time) *PostUpdate {
	_u.mutation.SetPublishTime(v)
	return _u
}

// SetNillablePublishTime sets the "publish_time" field if the given value is not nil.
func (_u *PostUpdate) SetNillablePublishTime(v *time.Time) *PostUpdate {
	if v != nil {
		_u.SetPublishTime(*v)
	}
	return _u
}

// ClearPublishTime clears the value of the "publish_time" field.
func (_u *PostUpdate) ClearPublishTime() *PostUpdate {
	_u.mutation.ClearPublishTime()
	return _u
}

// SetRenderVersion sets the "render_version" field.
func (_u *PostUpdate) SetRenderVersion(v int) *PostUpdate {
	_u.mutation.ResetRenderVersion()
	_u.mutation.SetRenderVersion(v)
	return _u
}

// SetNillableRenderVersion sets the "render_version" field if the given value is not nil.
func (_u *PostUpdate) SetNillableRenderVersion(v *int) *PostUpdate {
	if v != nil {
		_u.SetRenderVersion(*v)
	}
	return _u
}

// AddRenderVersion adds value to the "render_version" field.
func (_u *PostUpdate) AddRenderVersion(v int) *PostUpdate {
	_u.mutation.AddRenderVersion(v)
	return _u
}

// ClearRenderVersion clears the value of the "render_version" field.
func (_u *PostUpdate) ClearRenderVersion() *PostUpdate {
	_u.mutation.ClearRenderVersion()
	return _u
}

// SetState sets the "state" field.
func (_u *PostUpdate) SetState(v post.State) *PostUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *PostUpdate) SetNillableState(v *post.State) *PostUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetSubtitle sets the "subtitle" field.
func (_u *PostUpdate) SetSubtitle(v string) *PostUpdate {
	_u.mutation.SetSubtitle(v)
	return _u
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_u *PostUpdate) SetNillableSubtitle(v *string) *PostUpdate {
	if v != nil {
		_u.SetSubtitle(*v)
	}
	return _u
}

// ClearSubtitle clears the value of the "subtitle" field.
func (_u *PostUpdate) ClearSubtitle() *PostUpdate {
	_u.mutation.ClearSubtitle()
	return _u
}

// SetTitle sets the "title" field.
func (_u *PostUpdate) SetTitle(v string) *PostUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PostUpdate) SetNillableTitle(v *string) *PostUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// AddCategoryIDs adds the "categories" edge to the Category entity by IDs.
func (_u *PostUpdate) AddCategoryIDs(ids ...int) *PostUpdate {
	_u.mutation.AddCategoryIDs(ids...)
	return _u
}

// AddCategories adds the "categories" edges to the Category entity.
func (_u *PostUpdate) AddCategories(v ...*Category) *PostUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCategoryIDs(ids...)
}

// SetHeroImageID sets the "hero_image" edge to the Photo entity by ID.
func (_u *PostUpdate) SetHeroImageID(id int) *PostUpdate {
	_u.mutation.SetHeroImageID(id)
	return _u
}

// SetNillableHeroImageID sets the "hero_image" edge to the Photo entity by ID if the given value is not nil.
func (_u *PostUpdate) SetNillableHeroImageID(id *int) *PostUpdate {
	if id != nil {
		_u = _u.SetHeroImageID(*id)
	}
	return _u
}

// SetHeroImage sets the "hero_image" edge to the Photo entity.
func (_u *PostUpdate) SetHeroImage(v *Photo) *PostUpdate {
	return _u.SetHeroImageID(v.ID)
}

// AddRelatedPostIDs adds the "related_posts" edge to the Post entity by IDs.
func (_u *PostUpdate) AddRelatedPostIDs(ids ...int) *PostUpdate {
	_u.mutation.AddRelatedPostIDs(ids...)
	return _u
}

// AddRelatedPosts adds the "related_posts" edges to the Post entity.
func (_u *PostUpdate) AddRelatedPosts(v ...*Post) *PostUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRelatedPostIDs(ids...)
}

// SetSectionID sets the "section" edge to the Section entity by ID.
func (_u *PostUpdate) SetSectionID(id int) *PostUpdate {
	_u.mutation.SetSectionID(id)
	return _u
}

// SetNillableSectionID sets the "section" edge to the Section entity by ID if the given value is not nil.
func (_u *PostUpdate) SetNillableSectionID(id *int) *PostUpdate {
	if id != nil {
		_u = _u.SetSectionID(*id)
	}
	return _u
}

// SetSection sets the "section" edge to the Section entity.
func (_u *PostUpdate) SetSection(v *Section) *PostUpdate {
	return _u.SetSectionID(v.ID)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *PostUpdate) AddTagIDs(ids ...int) *PostUpdate {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *PostUpdate) AddTags(v ...*Tag) *PostUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// AddWriterIDs adds the "writers" edge to the Author entity by IDs.
func (_u *PostUpdate) AddWriterIDs(ids ...int) *PostUpdate {
	_u.mutation.AddWriterIDs(ids...)
	return _u
}

// AddWriters adds the "writers" edges to the Author entity.
func (_u *PostUpdate) AddWriters(v ...*Author) *PostUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWriterIDs(ids...)
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (_u *PostUpdate) SetCreatedByID(id int) *PostUpdate {
	_u.mutation.SetCreatedByID(id)
	return _u
}

// SetNillableCreatedByID sets the "created_by" edge to the User entity by ID if the given value is not nil.
func (_u *PostUpdate) SetNillableCreatedByID(id *int) *PostUpdate {
	if id != nil {
		_u = _u.SetCreatedByID(*id)
	}
	return _u
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_u *PostUpdate) SetCreatedBy(v *User) *PostUpdate {
	return _u.SetCreatedByID(v.ID)
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdate) Mutation() *PostMutation {
	return _u.mutation
}

// ClearCategories clears all "categories" edges to the Category entity.
func (_u *PostUpdate) ClearCategories() *PostUpdate {
	_u.mutation.ClearCategories()
	return _u
}

// RemoveCategoryIDs removes the "categories" edge to Category entities by IDs.
func (_u *PostUpdate) RemoveCategoryIDs(ids ...int) *PostUpdate {
	_u.mutation.RemoveCategoryIDs(ids...)
	return _u
}

// RemoveCategories removes "categories" edges to Category entities.
func (_u *PostUpdate) RemoveCategories(v ...*Category) *PostUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCategoryIDs(ids...)
}

// ClearHeroImage clears the "hero_image" edge to the Photo entity.
func (_u *PostUpdate) ClearHeroImage() *PostUpdate {
	_u.mutation.ClearHeroImage()
	return _u
}

// ClearRelatedPosts clears all "related_posts" edges to the Post entity.
func (_u *PostUpdate) ClearRelatedPosts() *PostUpdate {
	_u.mutation.ClearRelatedPosts()
	return _u
}

// RemoveRelatedPostIDs removes the "related_posts" edge to Post entities by IDs.
func (_u *PostUpdate) RemoveRelatedPostIDs(ids ...int) *PostUpdate {
	_u.mutation.RemoveRelatedPostIDs(ids...)
	return _u
}

// RemoveRelatedPosts removes "related_posts" edges to Post entities.
func (_u *PostUpdate) RemoveRelatedPosts(v ...*Post) *PostUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRelatedPostIDs(ids...)
}

// ClearSection clears the "section" edge to the Section entity.
func (_u *PostUpdate) ClearSection() *PostUpdate {
	_u.mutation.ClearSection()
	return _u
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *PostUpdate) ClearTags() *PostUpdate {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *PostUpdate) RemoveTagIDs(ids ...int) *PostUpdate {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *PostUpdate) RemoveTags(v ...*Tag) *PostUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// ClearWriters clears all "writers" edges to the Author entity.
func (_u *PostUpdate) ClearWriters() *PostUpdate {
	_u.mutation.ClearWriters()
	return _u
}

// RemoveWriterIDs removes the "writers" edge to Author entities by IDs.
func (_u *PostUpdate) RemoveWriterIDs(ids ...int) *PostUpdate {
	_u.mutation.RemoveWriterIDs(ids...)
	return _u
}

// RemoveWriters removes "writers" edges to Author entities.
func (_u *PostUpdate) RemoveWriters(v ...*Author) *PostUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWriterIDs(ids...)
}

// ClearCreatedBy clears the "created_by" edge to the User entity.
func (_u *PostUpdate) ClearCreatedBy() *PostUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PostUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PostUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := post.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostUpdate) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := post.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Post.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := post.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Post.title": %w`, err)}
		}
	}
	return nil
}

func (_u *PostUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Brief(); ok {
		_spec.SetField(post.FieldBrief, field.TypeJSON, value)
	}
	if _u.mutation.BriefCleared() {
		_spec.ClearField(post.FieldBrief, field.TypeJSON)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(post.FieldContent, field.TypeJSON, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(post.FieldContent, field.TypeJSON)
	}
	if value, ok := _u.mutation.ContentHTML(); ok {
		_spec.SetField(post.FieldContentHTML, field.TypeString, value)
	}
	if _u.mutation.ContentHTMLCleared() {
		_spec.ClearField(post.FieldContentHTML, field.TypeString)
	}
	if value, ok := _u.mutation.OtherByline(); ok {
		_spec.SetField(post.FieldOtherByline, field.TypeString, value)
	}
	if _u.mutation.OtherBylineCleared() {
		_spec.ClearField(post.FieldOtherByline, field.TypeString)
	}
	if value, ok := _u.mutation.PublishTime(); ok {
		_spec.SetField(post.FieldPublishTime, field.TypeTime, value)
	}
	if _u.mutation.PublishTimeCleared() {
		_spec.ClearField(post.FieldPublishTime, field.TypeTime)
	}
	if value, ok := _u.mutation.RenderVersion(); ok {
		_spec.SetField(post.FieldRenderVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRenderVersion(); ok {
		_spec.AddField(post.FieldRenderVersion, field.TypeInt, value)
	}
	if _u.mutation.RenderVersionCleared() {
		_spec.ClearField(post.FieldRenderVersion, field.TypeInt)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(post.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Subtitle(); ok {
		_spec.SetField(post.FieldSubtitle, field.TypeString, value)
	}
	if _u.mutation.SubtitleCleared() {
		_spec.ClearField(post.FieldSubtitle, field.TypeString)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(post.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.CategoriesTable,
			Columns: post.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCategoriesIDs(); len(nodes) > 0 && !_u.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.CategoriesTable,
			Columns: post.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.CategoriesTable,
			Columns: post.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HeroImageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.HeroImageTable,
			Columns: []string{post.HeroImageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(photo.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HeroImageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.HeroImageTable,
			Columns: []string{post.HeroImageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(photo.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RelatedPostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.RelatedPostsTable,
			Columns: post.RelatedPostsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRelatedPostsIDs(); len(nodes) > 0 && !_u.mutation.RelatedPostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.RelatedPostsTable,
			Columns: post.RelatedPostsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RelatedPostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.RelatedPostsTable,
			Columns: post.RelatedPostsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.SectionTable,
			Columns: []string{post.SectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.SectionTable,
			Columns: []string{post.SectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.TagsTable,
			Columns: post.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.TagsTable,
			Columns: post.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.TagsTable,
			Columns: post.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WritersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.WritersTable,
			Columns: post.WritersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWritersIDs(); len(nodes) > 0 && !_u.mutation.WritersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.WritersTable,
			Columns: post.WritersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WritersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.WritersTable,
			Columns: post.WritersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.CreatedByTable,
			Columns: []string{post.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.CreatedByTable,
			Columns: []string{post.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PostUpdateOne is the builder for updating a single Post entity.
type PostUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdateOne) SetUpdatedAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBrief sets the "brief" field.
func (_u *PostUpdateOne) SetBrief(v map[string]interface{}) *PostUpdateOne {
	_u.mutation.SetBrief(v)
	return _u
}

// ClearBrief clears the value of the "brief" field.
func (_u *PostUpdateOne) ClearBrief() *PostUpdateOne {
	_u.mutation.ClearBrief()
	return _u
}

// SetContent sets the "content" field.
func (_u *PostUpdateOne) SetContent(v map[string]interface{}) *PostUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *PostUpdateOne) ClearContent() *PostUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetContentHTML sets the "content_html" field.
func (_u *PostUpdateOne) SetContentHTML(v string) *PostUpdateOne {
	_u.mutation.SetContentHTML(v)
	return _u
}

// SetNillableContentHTML sets the "content_html" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableContentHTML(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetContentHTML(*v)
	}
	return _u
}

// ClearContentHTML clears the value of the "content_html" field.
func (_u *PostUpdateOne) ClearContentHTML() *PostUpdateOne {
	_u.mutation.ClearContentHTML()
	return _u
}

// SetOtherByline sets the "other_byline" field.
func (_u *PostUpdateOne) SetOtherByline(v string) *PostUpdateOne {
	_u.mutation.SetOtherByline(v)
	return _u
}

// SetNillableOtherByline sets the "other_byline" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableOtherByline(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetOtherByline(*v)
	}
	return _u
}

// ClearOtherByline clears the value of the "other_byline" field.
func (_u *PostUpdateOne) ClearOtherByline() *PostUpdateOne {
	_u.mutation.ClearOtherByline()
	return _u
}

// SetPublishTime sets the "publish_time" field.
func (_u *PostUpdateOne) SetPublishTime(v time.Time) *PostUpdateOne {
	_u.mutation.SetPublishTime(v)
	return _u
}

// SetNillablePublishTime sets the "publish_time" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillablePublishTime(v *time.Time) *PostUpdateOne {
	if v != nil {
		_u.SetPublishTime(*v)
	}
	return _u
}

// ClearPublishTime clears the value of the "publish_time" field.
func (_u *PostUpdateOne) ClearPublishTime() *PostUpdateOne {
	_u.mutation.ClearPublishTime()
	return _u
}

// SetRenderVersion sets the "render_version" field.
func (_u *PostUpdateOne) SetRenderVersion(v int) *PostUpdateOne {
	_u.mutation.ResetRenderVersion()
	_u.mutation.SetRenderVersion(v)
	return _u
}

// SetNillableRenderVersion sets the "render_version" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableRenderVersion(v *int) *PostUpdateOne {
	if v != nil {
		_u.SetRenderVersion(*v)
	}
	return _u
}

// AddRenderVersion adds value to the "render_version" field.
func (_u *PostUpdateOne) AddRenderVersion(v int) *PostUpdateOne {
	_u.mutation.AddRenderVersion(v)
	return _u
}

// ClearRenderVersion clears the value of the "render_version" field.
func (_u *PostUpdateOne) ClearRenderVersion() *PostUpdateOne {
	_u.mutation.ClearRenderVersion()
	return _u
}

// SetState sets the "state" field.
func (_u *PostUpdateOne) SetState(v post.State) *PostUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableState(v *post.State) *PostUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetSubtitle sets the "subtitle" field.
func (_u *PostUpdateOne) SetSubtitle(v string) *PostUpdateOne {
	_u.mutation.SetSubtitle(v)
	return _u
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableSubtitle(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetSubtitle(*v)
	}
	return _u
}

// ClearSubtitle clears the value of the "subtitle" field.
func (_u *PostUpdateOne) ClearSubtitle() *PostUpdateOne {
	_u.mutation.ClearSubtitle()
	return _u
}

// SetTitle sets the "title" field.
func (_u *PostUpdateOne) SetTitle(v string) *PostUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableTitle(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// AddCategoryIDs adds the "categories" edge to the Category entity by IDs.
func (_u *PostUpdateOne) AddCategoryIDs(ids ...int) *PostUpdateOne {
	_u.mutation.AddCategoryIDs(ids...)
	return _u
}

// AddCategories adds the "categories" edges to the Category entity.
func (_u *PostUpdateOne) AddCategories(v ...*Category) *PostUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCategoryIDs(ids...)
}

// SetHeroImageID sets the "hero_image" edge to the Photo entity by ID.
func (_u *PostUpdateOne) SetHeroImageID(id int) *PostUpdateOne {
	_u.mutation.SetHeroImageID(id)
	return _u
}

// SetNillableHeroImageID sets the "hero_image" edge to the Photo entity by ID if the given value is not nil.
func (_u *PostUpdateOne) SetNillableHeroImageID(id *int) *PostUpdateOne {
	if id != nil {
		_u = _u.SetHeroImageID(*id)
	}
	return _u
}

// SetHeroImage sets the "hero_image" edge to the Photo entity.
func (_u *PostUpdateOne) SetHeroImage(v *Photo) *PostUpdateOne {
	return _u.SetHeroImageID(v.ID)
}

// AddRelatedPostIDs adds the "related_posts" edge to the Post entity by IDs.
func (_u *PostUpdateOne) AddRelatedPostIDs(ids ...int) *PostUpdateOne {
	_u.mutation.AddRelatedPostIDs(ids...)
	return _u
}

// AddRelatedPosts adds the "related_posts" edges to the Post entity.
func (_u *PostUpdateOne) AddRelatedPosts(v ...*Post) *PostUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRelatedPostIDs(ids...)
}

// SetSectionID sets the "section" edge to the Section entity by ID.
func (_u *PostUpdateOne) SetSectionID(id int) *PostUpdateOne {
	_u.mutation.SetSectionID(id)
	return _u
}

// SetNillableSectionID sets the "section" edge to the Section entity by ID if the given value is not nil.
func (_u *PostUpdateOne) SetNillableSectionID(id *int) *PostUpdateOne {
	if id != nil {
		_u = _u.SetSectionID(*id)
	}
	return _u
}

// SetSection sets the "section" edge to the Section entity.
func (_u *PostUpdateOne) SetSection(v *Section) *PostUpdateOne {
	return _u.SetSectionID(v.ID)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *PostUpdateOne) AddTagIDs(ids ...int) *PostUpdateOne {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *PostUpdateOne) AddTags(v ...*Tag) *PostUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// AddWriterIDs adds the "writers" edge to the Author entity by IDs.
func (_u *PostUpdateOne) AddWriterIDs(ids ...int) *PostUpdateOne {
	_u.mutation.AddWriterIDs(ids...)
	return _u
}

// AddWriters adds the "writers" edges to the Author entity.
func (_u *PostUpdateOne) AddWriters(v ...*Author) *PostUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWriterIDs(ids...)
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (_u *PostUpdateOne) SetCreatedByID(id int) *PostUpdateOne {
	_u.mutation.SetCreatedByID(id)
	return _u
}

// SetNillableCreatedByID sets the "created_by" edge to the User entity by ID if the given value is not nil.
func (_u *PostUpdateOne) SetNillableCreatedByID(id *int) *PostUpdateOne {
	if id != nil {
		_u = _u.SetCreatedByID(*id)
	}
	return _u
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_u *PostUpdateOne) SetCreatedBy(v *User) *PostUpdateOne {
	return _u.SetCreatedByID(v.ID)
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdateOne) Mutation() *PostMutation {
	return _u.mutation
}

// ClearCategories clears all "categories" edges to the Category entity.
func (_u *PostUpdateOne) ClearCategories() *PostUpdateOne {
	_u.mutation.ClearCategories()
	return _u
}

// RemoveCategoryIDs removes the "categories" edge to Category entities by IDs.
func (_u *PostUpdateOne) RemoveCategoryIDs(ids ...int) *PostUpdateOne {
	_u.mutation.RemoveCategoryIDs(ids...)
	return _u
}

// RemoveCategories removes "categories" edges to Category entities.
func (_u *PostUpdateOne) RemoveCategories(v ...*Category) *PostUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCategoryIDs(ids...)
}

// ClearHeroImage clears the "hero_image" edge to the Photo entity.
func (_u *PostUpdateOne) ClearHeroImage() *PostUpdateOne {
	_u.mutation.ClearHeroImage()
	return _u
}

// ClearRelatedPosts clears all "related_posts" edges to the Post entity.
func (_u *PostUpdateOne) ClearRelatedPosts() *PostUpdateOne {
	_u.mutation.ClearRelatedPosts()
	return _u
}

// RemoveRelatedPostIDs removes the "related_posts" edge to Post entities by IDs.
func (_u *PostUpdateOne) RemoveRelatedPostIDs(ids ...int) *PostUpdateOne {
	_u.mutation.RemoveRelatedPostIDs(ids...)
	return _u
}

// RemoveRelatedPosts removes "related_posts" edges to Post entities.
func (_u *PostUpdateOne) RemoveRelatedPosts(v ...*Post) *PostUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRelatedPostIDs(ids...)
}

// ClearSection clears the "section" edge to the Section entity.
func (_u *PostUpdateOne) ClearSection() *PostUpdateOne {
	_u.mutation.ClearSection()
	return _u
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *PostUpdateOne) ClearTags() *PostUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *PostUpdateOne) RemoveTagIDs(ids ...int) *PostUpdateOne {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *PostUpdateOne) RemoveTags(v ...*Tag) *PostUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// ClearWriters clears all "writers" edges to the Author entity.
func (_u *PostUpdateOne) ClearWriters() *PostUpdateOne {
	_u.mutation.ClearWriters()
	return _u
}

// RemoveWriterIDs removes the "writers" edge to Author entities by IDs.
func (_u *PostUpdateOne) RemoveWriterIDs(ids ...int) *PostUpdateOne {
	_u.mutation.RemoveWriterIDs(ids...)
	return _u
}

// RemoveWriters removes "writers" edges to Author entities.
func (_u *PostUpdateOne) RemoveWriters(v ...*Author) *PostUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWriterIDs(ids...)
}

// ClearCreatedBy clears the "created_by" edge to the User entity.
func (_u *PostUpdateOne) ClearCreatedBy() *PostUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdateOne) Where(ps ...predicate.Post) *PostUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PostUpdateOne) Select(field string, fields ...string) *PostUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Post entity.
func (_u *PostUpdateOne) Save(ctx context.Context) (*Post, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdateOne) SaveX(ctx context.Context) *Post {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PostUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := post.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostUpdateOne) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := post.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Post.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := post.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Post.title": %w`, err)}
		}
	}
	return nil
}

func (_u *PostUpdateOne) sqlSave(ctx context.Context) (_node *Post, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Post.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, post.FieldID)
		for _, f := range fields {
			if !post.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != post.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Brief(); ok {
		_spec.SetField(post.FieldBrief, field.TypeJSON, value)
	}
	if _u.mutation.BriefCleared() {
		_spec.ClearField(post.FieldBrief, field.TypeJSON)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(post.FieldContent, field.TypeJSON, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(post.FieldContent, field.TypeJSON)
	}
	if value, ok := _u.mutation.ContentHTML(); ok {
		_spec.SetField(post.FieldContentHTML, field.TypeString, value)
	}
	if _u.mutation.ContentHTMLCleared() {
		_spec.ClearField(post.FieldContentHTML, field.TypeString)
	}
	if value, ok := _u.mutation.OtherByline(); ok {
		_spec.SetField(post.FieldOtherByline, field.TypeString, value)
	}
	if _u.mutation.OtherBylineCleared() {
		_spec.ClearField(post.FieldOtherByline, field.TypeString)
	}
	if value, ok := _u.mutation.PublishTime(); ok {
		_spec.SetField(post.FieldPublishTime, field.TypeTime, value)
	}
	if _u.mutation.PublishTimeCleared() {
		_spec.ClearField(post.FieldPublishTime, field.TypeTime)
	}
	if value, ok := _u.mutation.RenderVersion(); ok {
		_spec.SetField(post.FieldRenderVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRenderVersion(); ok {
		_spec.AddField(post.FieldRenderVersion, field.TypeInt, value)
	}
	if _u.mutation.RenderVersionCleared() {
		_spec.ClearField(post.FieldRenderVersion, field.TypeInt)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(post.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Subtitle(); ok {
		_spec.SetField(post.FieldSubtitle, field.TypeString, value)
	}
	if _u.mutation.SubtitleCleared() {
		_spec.ClearField(post.FieldSubtitle, field.TypeString)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(post.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.CategoriesTable,
			Columns: post.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCategoriesIDs(); len(nodes) > 0 && !_u.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.CategoriesTable,
			Columns: post.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.CategoriesTable,
			Columns: post.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HeroImageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.HeroImageTable,
			Columns: []string{post.HeroImageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(photo.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HeroImageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.HeroImageTable,
			Columns: []string{post.HeroImageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(photo.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RelatedPostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.RelatedPostsTable,
			Columns: post.RelatedPostsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRelatedPostsIDs(); len(nodes) > 0 && !_u.mutation.RelatedPostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.RelatedPostsTable,
			Columns: post.RelatedPostsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RelatedPostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.RelatedPostsTable,
			Columns: post.RelatedPostsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.SectionTable,
			Columns: []string{post.SectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.SectionTable,
			Columns: []string{post.SectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.TagsTable,
			Columns: post.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.TagsTable,
			Columns: post.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.TagsTable,
			Columns: post.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WritersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.WritersTable,
			Columns: post.WritersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWritersIDs(); len(nodes) > 0 && !_u.mutation.WritersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.WritersTable,
			Columns: post.WritersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WritersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.WritersTable,
			Columns: post.WritersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.CreatedByTable,
			Columns: []string{post.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.CreatedByTable,
			Columns: []string{post.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Post{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
