// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hcchien/nl/ent/author"
	"github.com/hcchien/nl/ent/category"
	"github.com/hcchien/nl/ent/photo"
	"github.com/hcchien/nl/ent/post"
	"github.com/hcchien/nl/ent/section"
	"github.com/hcchien/nl/ent/tag"
	"github.com/hcchien/nl/ent/user"
)

// PostCreate is the builder for creating a Post entity.
type PostCreate struct {
	config
	mutation *PostMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *PostCreate) SetCreatedAt(v time.Time) *PostCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PostCreate) SetNillableCreatedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PostCreate) SetUpdatedAt(v time.Time) *PostCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PostCreate) SetNillableUpdatedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetBrief sets the "brief" field.
func (_c *PostCreate) SetBrief(v map[string]interface{}) *PostCreate {
	_c.mutation.SetBrief(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *PostCreate) SetContent(v map[string]interface{}) *PostCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetContentHTML sets the "content_html" field.
func (_c *PostCreate) SetContentHTML(v string) *PostCreate {
	_c.mutation.SetContentHTML(v)
	return _c
}

// SetNillableContentHTML sets the "content_html" field if the given value is not nil.
func (_c *PostCreate) SetNillableContentHTML(v *string) *PostCreate {
	if v != nil {
		_c.SetContentHTML(*v)
	}
	return _c
}

// SetOtherByline sets the "other_byline" field.
func (_c *PostCreate) SetOtherByline(v string) *PostCreate {
	_c.mutation.SetOtherByline(v)
	return _c
}

// SetNillableOtherByline sets the "other_byline" field if the given value is not nil.
func (_c *PostCreate) SetNillableOtherByline(v *string) *PostCreate {
	if v != nil {
		_c.SetOtherByline(*v)
	}
	return _c
}

// SetPublishTime sets the "publish_time" field.
func (_c *PostCreate) SetPublishTime(v time.Time) *PostCreate {
	_c.mutation.SetPublishTime(v)
	return _c
}

// SetNillablePublishTime sets the "publish_time" field if the given value is not nil.
func (_c *PostCreate) SetNillablePublishTime(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetPublishTime(*v)
	}
	return _c
}

// SetRenderVersion sets the "render_version" field.
func (_c *PostCreate) SetRenderVersion(v int) *PostCreate {
	_c.mutation.SetRenderVersion(v)
	return _c
}

// SetNillableRenderVersion sets the "render_version" field if the given value is not nil.
func (_c *PostCreate) SetNillableRenderVersion(v *int) *PostCreate {
	if v != nil {
		_c.SetRenderVersion(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *PostCreate) SetState(v post.State) *PostCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *PostCreate) SetNillableState(v *post.State) *PostCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetSubtitle sets the "subtitle" field.
func (_c *PostCreate) SetSubtitle(v string) *PostCreate {
	_c.mutation.SetSubtitle(v)
	return _c
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_c *PostCreate) SetNillableSubtitle(v *string) *PostCreate {
	if v != nil {
		_c.SetSubtitle(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *PostCreate) SetTitle(v string) *PostCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// AddCategoryIDs adds the "categories" edge to the Category entity by IDs.
func (_c *PostCreate) AddCategoryIDs(ids ...int) *PostCreate {
	_c.mutation.AddCategoryIDs(ids...)
	return _c
}

// AddCategories adds the "categories" edges to the Category entity.
func (_c *PostCreate) AddCategories(v ...*Category) *PostCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCategoryIDs(ids...)
}

// SetHeroImageID sets the "hero_image" edge to the Photo entity by ID.
func (_c *PostCreate) SetHeroImageID(id int) *PostCreate {
	_c.mutation.SetHeroImageID(id)
	return _c
}

// SetNillableHeroImageID sets the "hero_image" edge to the Photo entity by ID if the given value is not nil.
func (_c *PostCreate) SetNillableHeroImageID(id *int) *PostCreate {
	if id != nil {
		_c = _c.SetHeroImageID(*id)
	}
	return _c
}

// SetHeroImage sets the "hero_image" edge to the Photo entity.
func (_c *PostCreate) SetHeroImage(v *Photo) *PostCreate {
	return _c.SetHeroImageID(v.ID)
}

// AddRelatedPostIDs adds the "related_posts" edge to the Post entity by IDs.
func (_c *PostCreate) AddRelatedPostIDs(ids ...int) *PostCreate {
	_c.mutation.AddRelatedPostIDs(ids...)
	return _c
}

// AddRelatedPosts adds the "related_posts" edges to the Post entity.
func (_c *PostCreate) AddRelatedPosts(v ...*Post) *PostCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRelatedPostIDs(ids...)
}

// SetSectionID sets the "section" edge to the Section entity by ID.
func (_c *PostCreate) SetSectionID(id int) *PostCreate {
	_c.mutation.SetSectionID(id)
	return _c
}

// SetNillableSectionID sets the "section" edge to the Section entity by ID if the given value is not nil.
func (_c *PostCreate) SetNillableSectionID(id *int) *PostCreate {
	if id != nil {
		_c = _c.SetSectionID(*id)
	}
	return _c
}

// SetSection sets the "section" edge to the Section entity.
func (_c *PostCreate) SetSection(v *Section) *PostCreate {
	return _c.SetSectionID(v.ID)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_c *PostCreate) AddTagIDs(ids ...int) *PostCreate {
	_c.mutation.AddTagIDs(ids...)
	return _c
}

// AddTags adds the "tags" edges to the Tag entity.
func (_c *PostCreate) AddTags(v ...*Tag) *PostCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTagIDs(ids...)
}

// AddWriterIDs adds the "writers" edge to the Author entity by IDs.
func (_c *PostCreate) AddWriterIDs(ids ...int) *PostCreate {
	_c.mutation.AddWriterIDs(ids...)
	return _c
}

// AddWriters adds the "writers" edges to the Author entity.
func (_c *PostCreate) AddWriters(v ...*Author) *PostCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddWriterIDs(ids...)
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (_c *PostCreate) SetCreatedByID(id int) *PostCreate {
	_c.mutation.SetCreatedByID(id)
	return _c
}

// SetNillableCreatedByID sets the "created_by" edge to the User entity by ID if the given value is not nil.
func (_c *PostCreate) SetNillableCreatedByID(id *int) *PostCreate {
	if id != nil {
		_c = _c.SetCreatedByID(*id)
	}
	return _c
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_c *PostCreate) SetCreatedBy(v *User) *PostCreate {
	return _c.SetCreatedByID(v.ID)
}

// Mutation returns the PostMutation object of the builder.
func (_c *PostCreate) Mutation() *PostMutation {
	return _c.mutation
}

// Save creates the Post in the database.
func (_c *PostCreate) Save(ctx context.Context) (*Post, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PostCreate) SaveX(ctx context.Context) *Post {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PostCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := post.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := post.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.RenderVersion(); !ok {
		v := post.DefaultRenderVersion
		_c.mutation.SetRenderVersion(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := post.DefaultState
		_c.mutation.SetState(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PostCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Post.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Post.updated_at"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Post.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := post.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Post.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Post.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := post.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Post.title": %w`, err)}
		}
	}
	return nil
}

func (_c *PostCreate) sqlSave(ctx context.Context) (*Post, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PostCreate) createSpec() (*Post, *sqlgraph.CreateSpec) {
	var (
		_node = &Post{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(post.Table, sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(post.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Brief(); ok {
		_spec.SetField(post.FieldBrief, field.TypeJSON, value)
		_node.Brief = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(post.FieldContent, field.TypeJSON, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.ContentHTML(); ok {
		_spec.SetField(post.FieldContentHTML, field.TypeString, value)
		_node.ContentHTML = value
	}
	if value, ok := _c.mutation.OtherByline(); ok {
		_spec.SetField(post.FieldOtherByline, field.TypeString, value)
		_node.OtherByline = value
	}
	if value, ok := _c.mutation.PublishTime(); ok {
		_spec.SetField(post.FieldPublishTime, field.TypeTime, value)
		_node.PublishTime = &value
	}
	if value, ok := _c.mutation.RenderVersion(); ok {
		_spec.SetField(post.FieldRenderVersion, field.TypeInt, value)
		_node.RenderVersion = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(post.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.Subtitle(); ok {
		_spec.SetField(post.FieldSubtitle, field.TypeString, value)
		_node.Subtitle = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(post.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if nodes := _c.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.CategoriesTable,
			Columns: post.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.HeroImageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.HeroImageTable,
			Columns: []string{post.HeroImageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(photo.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.post_hero_image = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RelatedPostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.RelatedPostsTable,
			Columns: post.RelatedPostsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.SectionTable,
			Columns: []string{post.SectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.post_section = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.TagsTable,
			Columns: post.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WritersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.WritersTable,
			Columns: post.WritersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.CreatedByTable,
			Columns: []string{post.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.post_created_by = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PostCreateBulk is the builder for creating many Post entities in bulk.
type PostCreateBulk struct {
	config
	err      error
	builders []*PostCreate
}

// Save creates the Post entities in the database.
func (_c *PostCreateBulk) Save(ctx context.Context) ([]*Post, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Post, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PostCreateBulk) SaveX(ctx context.Context) []*Post {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
