// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/hcchien/nl/ent/photo"
	"github.com/hcchien/nl/ent/post"
	"github.com/hcchien/nl/ent/section"
	"github.com/hcchien/nl/ent/user"
)

// Post is the model entity for the Post schema.
type Post struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Brief holds the value of the "brief" field.
	Brief map[string]interface{} `json:"brief,omitempty"`
	// Content holds the value of the "content" field.
	Content map[string]interface{} `json:"content,omitempty"`
	// ContentHTML holds the value of the "content_html" field.
	ContentHTML string `json:"content_html,omitempty"`
	// OtherByline holds the value of the "other_byline" field.
	OtherByline string `json:"other_byline,omitempty"`
	// PublishTime holds the value of the "publish_time" field.
	PublishTime *time.Time `json:"publish_time,omitempty"`
	// RenderVersion holds the value of the "render_version" field.
	RenderVersion int `json:"render_version,omitempty"`
	// State holds the value of the "state" field.
	State post.State `json:"state,omitempty"`
	// Subtitle holds the value of the "subtitle" field.
	Subtitle string `json:"subtitle,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PostQuery when eager-loading is set.
	Edges           PostEdges `json:"edges"`
	post_hero_image *int
	post_section    *int
	post_created_by *int
	selectValues    sql.SelectValues
}

// PostEdges holds the relations/edges for other nodes in the graph.
type PostEdges struct {
	// Categories holds the value of the categories edge.
	Categories []*Category `json:"categories,omitempty"`
	// HeroImage holds the value of the hero_image edge.
	HeroImage *Photo `json:"hero_image,omitempty"`
	// RelatedPosts holds the value of the related_posts edge.
	RelatedPosts []*Post `json:"related_posts,omitempty"`
	// Section holds the value of the section edge.
	Section *Section `json:"section,omitempty"`
	// Tags holds the value of the tags edge.
	Tags []*Tag `json:"tags,omitempty"`
	// Writers holds the value of the writers edge.
	Writers []*Author `json:"writers,omitempty"`
	// CreatedBy holds the value of the created_by edge.
	CreatedBy *User `json:"created_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [7]bool
	// totalCount holds the count of the edges above.
	totalCount [7]map[string]int

	namedCategories   map[string][]*Category
	namedRelatedPosts map[string][]*Post
	namedTags         map[string][]*Tag
	namedWriters      map[string][]*Author
}

// CategoriesOrErr returns the Categories value or an error if the edge
// was not loaded in eager-loading.
func (e PostEdges) CategoriesOrErr() ([]*Category, error) {
	if e.loadedTypes[0] {
		return e.Categories, nil
	}
	return nil, &NotLoadedError{edge: "categories"}
}

// HeroImageOrErr returns the HeroImage value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostEdges) HeroImageOrErr() (*Photo, error) {
	if e.HeroImage != nil {
		return e.HeroImage, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: photo.Label}
	}
	return nil, &NotLoadedError{edge: "hero_image"}
}

// RelatedPostsOrErr returns the RelatedPosts value or an error if the edge
// was not loaded in eager-loading.
func (e PostEdges) RelatedPostsOrErr() ([]*Post, error) {
	if e.loadedTypes[2] {
		return e.RelatedPosts, nil
	}
	return nil, &NotLoadedError{edge: "related_posts"}
}

// SectionOrErr returns the Section value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostEdges) SectionOrErr() (*Section, error) {
	if e.Section != nil {
		return e.Section, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: section.Label}
	}
	return nil, &NotLoadedError{edge: "section"}
}

// TagsOrErr returns the Tags value or an error if the edge
// was not loaded in eager-loading.
func (e PostEdges) TagsOrErr() ([]*Tag, error) {
	if e.loadedTypes[4] {
		return e.Tags, nil
	}
	return nil, &NotLoadedError{edge: "tags"}
}

// WritersOrErr returns the Writers value or an error if the edge
// was not loaded in eager-loading.
func (e PostEdges) WritersOrErr() ([]*Author, error) {
	if e.loadedTypes[5] {
		return e.Writers, nil
	}
	return nil, &NotLoadedError{edge: "writers"}
}

// CreatedByOrErr returns the CreatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostEdges) CreatedByOrErr() (*User, error) {
	if e.CreatedBy != nil {
		return e.CreatedBy, nil
	} else if e.loadedTypes[6] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "created_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Post) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case post.FieldBrief, post.FieldContent:
			values[i] = new([]byte)
		case post.FieldID, post.FieldRenderVersion:
			values[i] = new(sql.NullInt64)
		case post.FieldContentHTML, post.FieldOtherByline, post.FieldState, post.FieldSubtitle, post.FieldTitle:
			values[i] = new(sql.NullString)
		case post.FieldCreatedAt, post.FieldUpdatedAt, post.FieldPublishTime:
			values[i] = new(sql.NullTime)
		case post.ForeignKeys[0]: // post_hero_image
			values[i] = new(sql.NullInt64)
		case post.ForeignKeys[1]: // post_section
			values[i] = new(sql.NullInt64)
		case post.ForeignKeys[2]: // post_created_by
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Post fields.
func (_m *Post) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case post.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case post.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case post.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case post.FieldBrief:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field brief", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Brief); err != nil {
					return fmt.Errorf("unmarshal field brief: %w", err)
				}
			}
		case post.FieldContent:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Content); err != nil {
					return fmt.Errorf("unmarshal field content: %w", err)
				}
			}
		case post.FieldContentHTML:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_html", values[i])
			} else if value.Valid {
				_m.ContentHTML = value.String
			}
		case post.FieldOtherByline:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field other_byline", values[i])
			} else if value.Valid {
				_m.OtherByline = value.String
			}
		case post.FieldPublishTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field publish_time", values[i])
			} else if value.Valid {
				_m.PublishTime = new(time.Time)
				*_m.PublishTime = value.Time
			}
		case post.FieldRenderVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field render_version", values[i])
			} else if value.Valid {
				_m.RenderVersion = int(value.Int64)
			}
		case post.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = post.State(value.String)
			}
		case post.FieldSubtitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subtitle", values[i])
			} else if value.Valid {
				_m.Subtitle = value.String
			}
		case post.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case post.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field post_hero_image", value)
			} else if value.Valid {
				_m.post_hero_image = new(int)
				*_m.post_hero_image = int(value.Int64)
			}
		case post.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field post_section", value)
			} else if value.Valid {
				_m.post_section = new(int)
				*_m.post_section = int(value.Int64)
			}
		case post.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field post_created_by", value)
			} else if value.Valid {
				_m.post_created_by = new(int)
				*_m.post_created_by = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Post.
// This includes values selected through modifiers, order, etc.
func (_m *Post) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCategories queries the "categories" edge of the Post entity.
func (_m *Post) QueryCategories() *CategoryQuery {
	return NewPostClient(_m.config).QueryCategories(_m)
}

// QueryHeroImage queries the "hero_image" edge of the Post entity.
func (_m *Post) QueryHeroImage() *PhotoQuery {
	return NewPostClient(_m.config).QueryHeroImage(_m)
}

// QueryRelatedPosts queries the "related_posts" edge of the Post entity.
func (_m *Post) QueryRelatedPosts() *PostQuery {
	return NewPostClient(_m.config).QueryRelatedPosts(_m)
}

// QuerySection queries the "section" edge of the Post entity.
func (_m *Post) QuerySection() *SectionQuery {
	return NewPostClient(_m.config).QuerySection(_m)
}

// QueryTags queries the "tags" edge of the Post entity.
func (_m *Post) QueryTags() *TagQuery {
	return NewPostClient(_m.config).QueryTags(_m)
}

// QueryWriters queries the "writers" edge of the Post entity.
func (_m *Post) QueryWriters() *AuthorQuery {
	return NewPostClient(_m.config).QueryWriters(_m)
}

// QueryCreatedBy queries the "created_by" edge of the Post entity.
func (_m *Post) QueryCreatedBy() *UserQuery {
	return NewPostClient(_m.config).QueryCreatedBy(_m)
}

// Update returns a builder for updating this Post.
// Note that you need to call Post.Unwrap() before calling this method if this Post
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Post) Update() *PostUpdateOne {
	return NewPostClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Post entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Post) Unwrap() *Post {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Post is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Post) String() string {
	var builder strings.Builder
	builder.WriteString("Post(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("brief=")
	builder.WriteString(fmt.Sprintf("%v", _m.Brief))
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(fmt.Sprintf("%v", _m.Content))
	builder.WriteString(", ")
	builder.WriteString("content_html=")
	builder.WriteString(_m.ContentHTML)
	builder.WriteString(", ")
	builder.WriteString("other_byline=")
	builder.WriteString(_m.OtherByline)
	builder.WriteString(", ")
	if v := _m.PublishTime; v != nil {
		builder.WriteString("publish_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("render_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.RenderVersion))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	builder.WriteString("subtitle=")
	builder.WriteString(_m.Subtitle)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteByte(')')
	return builder.String()
}

// NamedCategories returns the Categories named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Post) NamedCategories(name string) ([]*Category, error) {
	if _m.Edges.namedCategories == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedCategories[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Post) appendNamedCategories(name string, edges ...*Category) {
	if _m.Edges.namedCategories == nil {
		_m.Edges.namedCategories = make(map[string][]*Category)
	}
	if len(edges) == 0 {
		_m.Edges.namedCategories[name] = []*Category{}
	} else {
		_m.Edges.namedCategories[name] = append(_m.Edges.namedCategories[name], edges...)
	}
}

// NamedRelatedPosts returns the RelatedPosts named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Post) NamedRelatedPosts(name string) ([]*Post, error) {
	if _m.Edges.namedRelatedPosts == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedRelatedPosts[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Post) appendNamedRelatedPosts(name string, edges ...*Post) {
	if _m.Edges.namedRelatedPosts == nil {
		_m.Edges.namedRelatedPosts = make(map[string][]*Post)
	}
	if len(edges) == 0 {
		_m.Edges.namedRelatedPosts[name] = []*Post{}
	} else {
		_m.Edges.namedRelatedPosts[name] = append(_m.Edges.namedRelatedPosts[name], edges...)
	}
}

// NamedTags returns the Tags named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Post) NamedTags(name string) ([]*Tag, error) {
	if _m.Edges.namedTags == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedTags[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Post) appendNamedTags(name string, edges ...*Tag) {
	if _m.Edges.namedTags == nil {
		_m.Edges.namedTags = make(map[string][]*Tag)
	}
	if len(edges) == 0 {
		_m.Edges.namedTags[name] = []*Tag{}
	} else {
		_m.Edges.namedTags[name] = append(_m.Edges.namedTags[name], edges...)
	}
}

// NamedWriters returns the Writers named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Post) NamedWriters(name string) ([]*Author, error) {
	if _m.Edges.namedWriters == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedWriters[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Post) appendNamedWriters(name string, edges ...*Author) {
	if _m.Edges.namedWriters == nil {
		_m.Edges.namedWriters = make(map[string][]*Author)
	}
	if len(edges) == 0 {
		_m.Edges.namedWriters[name] = []*Author{}
	} else {
		_m.Edges.namedWriters[name] = append(_m.Edges.namedWriters[name], edges...)
	}
}

// Posts is a parsable slice of Post.
type Posts []*Post
