// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/hcchien/nl/ent/apikey"
	"github.com/hcchien/nl/ent/author"
	"github.com/hcchien/nl/ent/category"
	"github.com/hcchien/nl/ent/oauthclient"
	"github.com/hcchien/nl/ent/oauthcode"
	"github.com/hcchien/nl/ent/oauthrefresh"
	"github.com/hcchien/nl/ent/photo"
	"github.com/hcchien/nl/ent/post"
	"github.com/hcchien/nl/ent/schema"
	"github.com/hcchien/nl/ent/section"
	"github.com/hcchien/nl/ent/tag"
	"github.com/hcchien/nl/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apikeyMixin := schema.ApiKey{}.Mixin()
	apikeyMixinFields0 := apikeyMixin[0].Fields()
	_ = apikeyMixinFields0
	apikeyFields := schema.ApiKey{}.Fields()
	_ = apikeyFields
	// apikeyDescCreatedAt is the schema descriptor for created_at field.
	apikeyDescCreatedAt := apikeyMixinFields0[0].Descriptor()
	// apikey.DefaultCreatedAt holds the default value on creation for the created_at field.
	apikey.DefaultCreatedAt = apikeyDescCreatedAt.Default.(func() time.Time)
	// apikeyDescUpdatedAt is the schema descriptor for updated_at field.
	apikeyDescUpdatedAt := apikeyMixinFields0[1].Descriptor()
	// apikey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	apikey.DefaultUpdatedAt = apikeyDescUpdatedAt.Default.(func() time.Time)
	// apikey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	apikey.UpdateDefaultUpdatedAt = apikeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// apikeyDescName is the schema descriptor for name field.
	apikeyDescName := apikeyFields[1].Descriptor()
	// apikey.NameValidator is a validator for the "name" field. It is called by the builders before save.
	apikey.NameValidator = apikeyDescName.Validators[0].(func(string) error)
	// apikeyDescKeyHash is the schema descriptor for key_hash field.
	apikeyDescKeyHash := apikeyFields[2].Descriptor()
	// apikey.KeyHashValidator is a validator for the "key_hash" field. It is called by the builders before save.
	apikey.KeyHashValidator = apikeyDescKeyHash.Validators[0].(func(string) error)
	authorMixin := schema.Author{}.Mixin()
	authorMixinFields0 := authorMixin[0].Fields()
	_ = authorMixinFields0
	authorFields := schema.Author{}.Fields()
	_ = authorFields
	// authorDescCreatedAt is the schema descriptor for created_at field.
	authorDescCreatedAt := authorMixinFields0[0].Descriptor()
	// author.DefaultCreatedAt holds the default value on creation for the created_at field.
	author.DefaultCreatedAt = authorDescCreatedAt.Default.(func() time.Time)
	// authorDescUpdatedAt is the schema descriptor for updated_at field.
	authorDescUpdatedAt := authorMixinFields0[1].Descriptor()
	// author.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	author.DefaultUpdatedAt = authorDescUpdatedAt.Default.(func() time.Time)
	// author.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	author.UpdateDefaultUpdatedAt = authorDescUpdatedAt.UpdateDefault.(func() time.Time)
	// authorDescName is the schema descriptor for name field.
	authorDescName := authorFields[1].Descriptor()
	// author.NameValidator is a validator for the "name" field. It is called by the builders before save.
	author.NameValidator = authorDescName.Validators[0].(func(string) error)
	categoryMixin := schema.Category{}.Mixin()
	categoryMixinFields0 := categoryMixin[0].Fields()
	_ = categoryMixinFields0
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryMixinFields0[0].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	// categoryDescUpdatedAt is the schema descriptor for updated_at field.
	categoryDescUpdatedAt := categoryMixinFields0[1].Descriptor()
	// category.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	category.DefaultUpdatedAt = categoryDescUpdatedAt.Default.(func() time.Time)
	// category.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	category.UpdateDefaultUpdatedAt = categoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[1].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = categoryDescName.Validators[0].(func(string) error)
	// categoryDescSlug is the schema descriptor for slug field.
	categoryDescSlug := categoryFields[2].Descriptor()
	// category.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	category.SlugValidator = func() func(string) error {
		validators := categoryDescSlug.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(slug string) error {
			for _, fn := range fns {
				if err := fn(slug); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	oauthclientMixin := schema.OAuthClient{}.Mixin()
	oauthclientMixinFields0 := oauthclientMixin[0].Fields()
	_ = oauthclientMixinFields0
	oauthclientFields := schema.OAuthClient{}.Fields()
	_ = oauthclientFields
	// oauthclientDescCreatedAt is the schema descriptor for created_at field.
	oauthclientDescCreatedAt := oauthclientMixinFields0[0].Descriptor()
	// oauthclient.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthclient.DefaultCreatedAt = oauthclientDescCreatedAt.Default.(func() time.Time)
	// oauthclientDescUpdatedAt is the schema descriptor for updated_at field.
	oauthclientDescUpdatedAt := oauthclientMixinFields0[1].Descriptor()
	// oauthclient.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthclient.DefaultUpdatedAt = oauthclientDescUpdatedAt.Default.(func() time.Time)
	// oauthclient.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthclient.UpdateDefaultUpdatedAt = oauthclientDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauthclientDescClientID is the schema descriptor for client_id field.
	oauthclientDescClientID := oauthclientFields[0].Descriptor()
	// oauthclient.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauthclient.ClientIDValidator = oauthclientDescClientID.Validators[0].(func(string) error)
	// oauthclientDescName is the schema descriptor for name field.
	oauthclientDescName := oauthclientFields[1].Descriptor()
	// oauthclient.DefaultName holds the default value on creation for the name field.
	oauthclient.DefaultName = oauthclientDescName.Default.(string)
	oauthcodeMixin := schema.OAuthCode{}.Mixin()
	oauthcodeMixinFields0 := oauthcodeMixin[0].Fields()
	_ = oauthcodeMixinFields0
	oauthcodeFields := schema.OAuthCode{}.Fields()
	_ = oauthcodeFields
	// oauthcodeDescCreatedAt is the schema descriptor for created_at field.
	oauthcodeDescCreatedAt := oauthcodeMixinFields0[0].Descriptor()
	// oauthcode.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthcode.DefaultCreatedAt = oauthcodeDescCreatedAt.Default.(func() time.Time)
	// oauthcodeDescUpdatedAt is the schema descriptor for updated_at field.
	oauthcodeDescUpdatedAt := oauthcodeMixinFields0[1].Descriptor()
	// oauthcode.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthcode.DefaultUpdatedAt = oauthcodeDescUpdatedAt.Default.(func() time.Time)
	// oauthcode.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthcode.UpdateDefaultUpdatedAt = oauthcodeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauthcodeDescCodeHash is the schema descriptor for code_hash field.
	oauthcodeDescCodeHash := oauthcodeFields[0].Descriptor()
	// oauthcode.CodeHashValidator is a validator for the "code_hash" field. It is called by the builders before save.
	oauthcode.CodeHashValidator = oauthcodeDescCodeHash.Validators[0].(func(string) error)
	// oauthcodeDescClientID is the schema descriptor for client_id field.
	oauthcodeDescClientID := oauthcodeFields[1].Descriptor()
	// oauthcode.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauthcode.ClientIDValidator = oauthcodeDescClientID.Validators[0].(func(string) error)
	// oauthcodeDescRedirectURI is the schema descriptor for redirect_uri field.
	oauthcodeDescRedirectURI := oauthcodeFields[2].Descriptor()
	// oauthcode.RedirectURIValidator is a validator for the "redirect_uri" field. It is called by the builders before save.
	oauthcode.RedirectURIValidator = oauthcodeDescRedirectURI.Validators[0].(func(string) error)
	// oauthcodeDescCodeChallenge is the schema descriptor for code_challenge field.
	oauthcodeDescCodeChallenge := oauthcodeFields[3].Descriptor()
	// oauthcode.CodeChallengeValidator is a validator for the "code_challenge" field. It is called by the builders before save.
	oauthcode.CodeChallengeValidator = oauthcodeDescCodeChallenge.Validators[0].(func(string) error)
	// oauthcodeDescExpiresAt is the schema descriptor for expires_at field.
	oauthcodeDescExpiresAt := oauthcodeFields[4].Descriptor()
	// oauthcode.DefaultExpiresAt holds the default value on creation for the expires_at field.
	oauthcode.DefaultExpiresAt = oauthcodeDescExpiresAt.Default.(func() time.Time)
	oauthrefreshMixin := schema.OAuthRefresh{}.Mixin()
	oauthrefreshMixinFields0 := oauthrefreshMixin[0].Fields()
	_ = oauthrefreshMixinFields0
	oauthrefreshFields := schema.OAuthRefresh{}.Fields()
	_ = oauthrefreshFields
	// oauthrefreshDescCreatedAt is the schema descriptor for created_at field.
	oauthrefreshDescCreatedAt := oauthrefreshMixinFields0[0].Descriptor()
	// oauthrefresh.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthrefresh.DefaultCreatedAt = oauthrefreshDescCreatedAt.Default.(func() time.Time)
	// oauthrefreshDescUpdatedAt is the schema descriptor for updated_at field.
	oauthrefreshDescUpdatedAt := oauthrefreshMixinFields0[1].Descriptor()
	// oauthrefresh.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthrefresh.DefaultUpdatedAt = oauthrefreshDescUpdatedAt.Default.(func() time.Time)
	// oauthrefresh.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthrefresh.UpdateDefaultUpdatedAt = oauthrefreshDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauthrefreshDescTokenHash is the schema descriptor for token_hash field.
	oauthrefreshDescTokenHash := oauthrefreshFields[0].Descriptor()
	// oauthrefresh.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	oauthrefresh.TokenHashValidator = oauthrefreshDescTokenHash.Validators[0].(func(string) error)
	// oauthrefreshDescClientID is the schema descriptor for client_id field.
	oauthrefreshDescClientID := oauthrefreshFields[1].Descriptor()
	// oauthrefresh.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauthrefresh.ClientIDValidator = oauthrefreshDescClientID.Validators[0].(func(string) error)
	photoMixin := schema.Photo{}.Mixin()
	photoMixinFields0 := photoMixin[0].Fields()
	_ = photoMixinFields0
	photoFields := schema.Photo{}.Fields()
	_ = photoFields
	// photoDescCreatedAt is the schema descriptor for created_at field.
	photoDescCreatedAt := photoMixinFields0[0].Descriptor()
	// photo.DefaultCreatedAt holds the default value on creation for the created_at field.
	photo.DefaultCreatedAt = photoDescCreatedAt.Default.(func() time.Time)
	// photoDescUpdatedAt is the schema descriptor for updated_at field.
	photoDescUpdatedAt := photoMixinFields0[1].Descriptor()
	// photo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	photo.DefaultUpdatedAt = photoDescUpdatedAt.Default.(func() time.Time)
	// photo.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	photo.UpdateDefaultUpdatedAt = photoDescUpdatedAt.UpdateDefault.(func() time.Time)
	// photoDescName is the schema descriptor for name field.
	photoDescName := photoFields[1].Descriptor()
	// photo.NameValidator is a validator for the "name" field. It is called by the builders before save.
	photo.NameValidator = photoDescName.Validators[0].(func(string) error)
	postMixin := schema.Post{}.Mixin()
	postMixinFields0 := postMixin[0].Fields()
	_ = postMixinFields0
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescCreatedAt is the schema descriptor for created_at field.
	postDescCreatedAt := postMixinFields0[0].Descriptor()
	// post.DefaultCreatedAt holds the default value on creation for the created_at field.
	post.DefaultCreatedAt = postDescCreatedAt.Default.(func() time.Time)
	// postDescUpdatedAt is the schema descriptor for updated_at field.
	postDescUpdatedAt := postMixinFields0[1].Descriptor()
	// post.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	post.DefaultUpdatedAt = postDescUpdatedAt.Default.(func() time.Time)
	// post.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	post.UpdateDefaultUpdatedAt = postDescUpdatedAt.UpdateDefault.(func() time.Time)
	// postDescRenderVersion is the schema descriptor for render_version field.
	postDescRenderVersion := postFields[5].Descriptor()
	// post.DefaultRenderVersion holds the default value on creation for the render_version field.
	post.DefaultRenderVersion = postDescRenderVersion.Default.(int)
	// postDescTitle is the schema descriptor for title field.
	postDescTitle := postFields[8].Descriptor()
	// post.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	post.TitleValidator = postDescTitle.Validators[0].(func(string) error)
	sectionMixin := schema.Section{}.Mixin()
	sectionMixinFields0 := sectionMixin[0].Fields()
	_ = sectionMixinFields0
	sectionFields := schema.Section{}.Fields()
	_ = sectionFields
	// sectionDescCreatedAt is the schema descriptor for created_at field.
	sectionDescCreatedAt := sectionMixinFields0[0].Descriptor()
	// section.DefaultCreatedAt holds the default value on creation for the created_at field.
	section.DefaultCreatedAt = sectionDescCreatedAt.Default.(func() time.Time)
	// sectionDescUpdatedAt is the schema descriptor for updated_at field.
	sectionDescUpdatedAt := sectionMixinFields0[1].Descriptor()
	// section.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	section.DefaultUpdatedAt = sectionDescUpdatedAt.Default.(func() time.Time)
	// section.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	section.UpdateDefaultUpdatedAt = sectionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// sectionDescName is the schema descriptor for name field.
	sectionDescName := sectionFields[1].Descriptor()
	// section.NameValidator is a validator for the "name" field. It is called by the builders before save.
	section.NameValidator = sectionDescName.Validators[0].(func(string) error)
	// sectionDescSlug is the schema descriptor for slug field.
	sectionDescSlug := sectionFields[2].Descriptor()
	// section.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	section.SlugValidator = func() func(string) error {
		validators := sectionDescSlug.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(slug string) error {
			for _, fn := range fns {
				if err := fn(slug); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	tagMixin := schema.Tag{}.Mixin()
	tagMixinFields0 := tagMixin[0].Fields()
	_ = tagMixinFields0
	tagFields := schema.Tag{}.Fields()
	_ = tagFields
	// tagDescCreatedAt is the schema descriptor for created_at field.
	tagDescCreatedAt := tagMixinFields0[0].Descriptor()
	// tag.DefaultCreatedAt holds the default value on creation for the created_at field.
	tag.DefaultCreatedAt = tagDescCreatedAt.Default.(func() time.Time)
	// tagDescUpdatedAt is the schema descriptor for updated_at field.
	tagDescUpdatedAt := tagMixinFields0[1].Descriptor()
	// tag.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tag.DefaultUpdatedAt = tagDescUpdatedAt.Default.(func() time.Time)
	// tag.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tag.UpdateDefaultUpdatedAt = tagDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tagDescIsFeatured is the schema descriptor for is_featured field.
	tagDescIsFeatured := tagFields[1].Descriptor()
	// tag.DefaultIsFeatured holds the default value on creation for the is_featured field.
	tag.DefaultIsFeatured = tagDescIsFeatured.Default.(bool)
	// tagDescName is the schema descriptor for name field.
	tagDescName := tagFields[2].Descriptor()
	// tag.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tag.NameValidator = tagDescName.Validators[0].(func(string) error)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
}
