// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type PublicAuthor struct {
	ID    int          `json:"id"`
	Name  string       `json:"name"`
	Bio   string       `json:"bio"`
	Image *PublicPhoto `json:"image,omitempty"`
}

type PublicCategory struct {
	ID          int            `json:"id"`
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Section     *PublicSection `json:"section,omitempty"`
}

type PublicPhoto struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	URL         string `json:"url"`
}

type PublicPost struct {
	ID       int    `json:"id"`
	Title    string `json:"title"`
	Subtitle string `json:"subtitle"`
	// 公開前言，沿用 CMS 的 ProseMirror JSON。
	Brief         map[string]any       `json:"brief,omitempty"`
	ContentHTML   string               `json:"contentHtml"`
	RenderVersion int                  `json:"renderVersion"`
	PublishTime   time.Time            `json:"publishTime"`
	UpdatedAt     time.Time            `json:"updatedAt"`
	OtherByline   string               `json:"otherByline"`
	HeroImage     *PublicPhoto         `json:"heroImage,omitempty"`
	Section       *PublicSection       `json:"section,omitempty"`
	Categories    []*PublicCategory    `json:"categories"`
	Tags          []*PublicTag         `json:"tags"`
	Writers       []*PublicAuthor      `json:"writers"`
	RelatedPosts  []*PublicPostSummary `json:"relatedPosts"`
}

type PublicPostPage struct {
	Items      []*PublicPost `json:"items"`
	TotalCount int           `json:"totalCount"`
	HasMore    bool          `json:"hasMore"`
}

type PublicPostSummary struct {
	ID          int       `json:"id"`
	Title       string    `json:"title"`
	Subtitle    string    `json:"subtitle"`
	PublishTime time.Time `json:"publishTime"`
}

type PublicSection struct {
	ID          int    `json:"id"`
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type PublicTag struct {
	ID         int    `json:"id"`
	Name       string `json:"name"`
	Brief      string `json:"brief"`
	IsFeatured bool   `json:"isFeatured"`
}

// 公開內容介面：所有查詢都需要 content:read 金鑰。
type Query struct {
}
