package contentgraph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/hcchien/nl/content"
	"github.com/hcchien/nl/contentgraph/model"
)

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id int) (*model.PublicPost, error) {
	p, err := r.Content.Post(ctx, id)
	if err != nil {
		return nil, err
	}
	return publicPost(p), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, first int, offset int, sectionSlug *string, categorySlug *string, tagID *int) (*model.PublicPostPage, error) {
	rows, count, err := r.Content.Posts(ctx, first, offset, content.Filter{SectionSlug: sectionSlug, CategorySlug: categorySlug, TagID: tagID})
	if err != nil {
		return nil, err
	}
	items := make([]*model.PublicPost, 0, len(rows))
	for _, p := range rows {
		items = append(items, publicPost(p))
	}
	return &model.PublicPostPage{Items: items, TotalCount: count, HasMore: offset+len(items) < count}, nil
}

// Sections is the resolver for the sections field.
func (r *queryResolver) Sections(ctx context.Context, first int, offset int) ([]*model.PublicSection, error) {
	rows, err := r.Content.Sections(ctx, first, offset)
	if err != nil {
		return nil, err
	}
	out := make([]*model.PublicSection, 0, len(rows))
	for _, row := range rows {
		out = append(out, publicSection(row))
	}
	return out, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context, first int, offset int) ([]*model.PublicCategory, error) {
	rows, err := r.Content.Categories(ctx, first, offset)
	if err != nil {
		return nil, err
	}
	out := make([]*model.PublicCategory, 0, len(rows))
	for _, row := range rows {
		out = append(out, publicCategory(row))
	}
	return out, nil
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context, first int, offset int) ([]*model.PublicTag, error) {
	rows, err := r.Content.Tags(ctx, first, offset)
	if err != nil {
		return nil, err
	}
	out := make([]*model.PublicTag, 0, len(rows))
	for _, row := range rows {
		out = append(out, publicTag(row))
	}
	return out, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
